import { NextResponse } from "next/server.js";
import { ADMIN_SESSION_COOKIE, isTrustedSameOriginRequest, readCookie, resolveAdminJwtSecret, verifyAdminSessionToken } from "../../../../worker/adminAuth.ts";

type D1Statement={bind:(...values:unknown[])=>D1Statement;run:()=>Promise<unknown>;all:<T=Record<string,unknown>>()=>Promise<{results:T[]}>};
type D1Database={prepare:(sql:string)=>D1Statement};
type MatchOverride={matchId:string;hidden:boolean;homeNameAr:string;awayNameAr:string;leagueNameAr:string;homeLogo:string;awayLogo:string;showHomeLogo:boolean;showAwayLogo:boolean;updatedAt:string};

const TEXT_LIMIT=120;
const cleanText=(value:unknown)=>typeof value==="string"?value.trim().slice(0,TEXT_LIMIT):"";
const cleanLogo=(value:unknown)=>{const url=cleanText(value);return /^https:\/\//i.test(url)?url:""};
const asFlag=(value:unknown)=>value===true||value===1||value==="1";
async function getDb():Promise<D1Database|null>{try{return (await import("cloudflare:workers") as {env?:{DB?:D1Database}}).env?.DB||null}catch{return (globalThis as {DB?:D1Database}).DB||null}}
async function ensureSchema(db:D1Database){await db.prepare("CREATE TABLE IF NOT EXISTS navixa_match_overrides (match_id TEXT PRIMARY KEY, hidden INTEGER NOT NULL DEFAULT 0, home_name_ar TEXT, away_name_ar TEXT, league_name_ar TEXT, home_logo TEXT, away_logo TEXT, show_home_logo INTEGER NOT NULL DEFAULT 1, show_away_logo INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL)").run()}
async function authorized(request:Request, mutation=false){if(mutation&&!isTrustedSameOriginRequest(request))return false;const secret=await resolveAdminJwtSecret();return Boolean(secret&&await verifyAdminSessionToken(readCookie(request,ADMIN_SESSION_COOKIE),secret))}
function toOverride(row:Record<string,unknown>):MatchOverride{return {matchId:String(row.match_id||""),hidden:Number(row.hidden||0)===1,homeNameAr:String(row.home_name_ar||""),awayNameAr:String(row.away_name_ar||""),leagueNameAr:String(row.league_name_ar||""),homeLogo:String(row.home_logo||""),awayLogo:String(row.away_logo||""),showHomeLogo:Number(row.show_home_logo??1)===1,showAwayLogo:Number(row.show_away_logo??1)===1,updatedAt:String(row.updated_at||"")}}

export async function GET(request:Request){if(!await authorized(request))return NextResponse.json({error:"غير مصرح"},{status:401,headers:{"Cache-Control":"no-store"}});const db=await getDb();if(!db)return NextResponse.json({configured:false,overrides:[]},{headers:{"Cache-Control":"no-store"}});await ensureSchema(db);const rows=await db.prepare("SELECT * FROM navixa_match_overrides ORDER BY updated_at DESC LIMIT 200").all<Record<string,unknown>>();return NextResponse.json({configured:true,overrides:rows.results.map(toOverride)},{headers:{"Cache-Control":"no-store"}})}

export async function POST(request:Request){if(!await authorized(request,true))return NextResponse.json({error:"غير مصرح"},{status:401,headers:{"Cache-Control":"no-store"}});const body=await request.json().catch(()=>({}));const matchId=cleanText(body.matchId);if(!matchId)return NextResponse.json({error:"معرّف المباراة مطلوب"},{status:400});const db=await getDb();if(!db)return NextResponse.json({error:"قاعدة البيانات غير مهيأة"},{status:503});await ensureSchema(db);const values=[matchId,asFlag(body.hidden)?1:0,cleanText(body.homeNameAr),cleanText(body.awayNameAr),cleanText(body.leagueNameAr),cleanLogo(body.homeLogo),cleanLogo(body.awayLogo),body.showHomeLogo===false?0:1,body.showAwayLogo===false?0:1,new Date().toISOString()];await db.prepare("INSERT INTO navixa_match_overrides (match_id,hidden,home_name_ar,away_name_ar,league_name_ar,home_logo,away_logo,show_home_logo,show_away_logo,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(match_id) DO UPDATE SET hidden=excluded.hidden,home_name_ar=excluded.home_name_ar,away_name_ar=excluded.away_name_ar,league_name_ar=excluded.league_name_ar,home_logo=excluded.home_logo,away_logo=excluded.away_logo,show_home_logo=excluded.show_home_logo,show_away_logo=excluded.show_away_logo,updated_at=excluded.updated_at").bind(...values).run();return NextResponse.json({ok:true},{headers:{"Cache-Control":"no-store"}})}

export async function DELETE(request:Request){if(!await authorized(request,true))return NextResponse.json({error:"غير مصرح"},{status:401,headers:{"Cache-Control":"no-store"}});const matchId=cleanText(new URL(request.url).searchParams.get("matchId"));if(!matchId)return NextResponse.json({error:"معرّف المباراة مطلوب"},{status:400});const db=await getDb();if(!db)return NextResponse.json({error:"قاعدة البيانات غير مهيأة"},{status:503});await ensureSchema(db);await db.prepare("DELETE FROM navixa_match_overrides WHERE match_id=?").bind(matchId).run();return NextResponse.json({ok:true},{headers:{"Cache-Control":"no-store"}})}
