"use client";

import {useEffect,useMemo,useState} from "react";

type Summary={waitlist:number;trial:number;active:number;endingSoon:number};
type Subscriber={id:string;contact:string;display_name:string;plan:"trial"|"monthly"|"quarterly";status:"waitlist"|"trial"|"active"|"paused"|"cancelled"|"expired";trial_started_at:string;trial_ends_at:string;subscription_ends_at:string;source:string;updated_at:string};
type BillingSettings={provider:"moyasar";mode:"test"|"live";public_checkout:"true"|"false";test_webhook_enabled:"true"|"false";live_payments_enabled:"true"|"false"};
type BillingSecrets={testKeyConfigured:boolean;testWebhookSecretConfigured:boolean;liveKeyConfigured:boolean;liveWebhookSecretConfigured:boolean};
type BillingEvent={id:string;provider_event_id:string;event_type:string;mode:"test"|"live";created_at:string;processed_at:string};
const headers={"Content-Type":"application/json"};
const planLabel:Record<Subscriber["plan"],string>={trial:"تجربة",monthly:"شهري",quarterly:"3 + 1"};
const statusLabel:Record<Subscriber["status"],string>={waitlist:"قائمة اهتمام",trial:"تجربة نشطة",active:"مشترك نشط",paused:"موقوف",cancelled:"ملغى",expired:"منتهي"};
const date=(value:string)=>value?new Intl.DateTimeFormat("ar-SA",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value)):"—";
const initialBilling:BillingSettings={provider:"moyasar",mode:"test",public_checkout:"false",test_webhook_enabled:"false",live_payments_enabled:"false"};
const initialSecrets:BillingSecrets={testKeyConfigured:false,testWebhookSecretConfigured:false,liveKeyConfigured:false,liveWebhookSecretConfigured:false};

export default function AdminSubscriptionSettings(){
  const [summary,setSummary]=useState<Summary>({waitlist:0,trial:0,active:0,endingSoon:0});const [subscribers,setSubscribers]=useState<Subscriber[]>([]);const [contact,setContact]=useState("");const [displayName,setDisplayName]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState("");
  const [billing,setBilling]=useState<BillingSettings>(initialBilling);const [secrets,setSecrets]=useState<BillingSecrets>(initialSecrets);const [events,setEvents]=useState<BillingEvent[]>([]);
  const load=async()=>{const [subscriptionResponse,billingResponse]=await Promise.all([fetch("/api/admin/subscriptions",{cache:"no-store"}),fetch("/api/admin/billing-settings",{cache:"no-store"})]);if(subscriptionResponse.ok){const data=await subscriptionResponse.json() as {summary:Summary;subscribers:Subscriber[]};setSummary(data.summary);setSubscribers(data.subscribers||[])}if(billingResponse.ok){const data=await billingResponse.json() as {settings:BillingSettings;secrets:BillingSecrets;events:BillingEvent[]};setBilling(data.settings||initialBilling);setSecrets(data.secrets||initialSecrets);setEvents(data.events||[])}};
  useEffect(()=>{void load()},[]);
  const addTrial=async()=>{setBusy("new");setNotice("");const response=await fetch("/api/admin/subscriptions",{method:"POST",headers,body:JSON.stringify({action:"create_trial",contact,displayName})});const data=await response.json().catch(()=>({}));setBusy("");if(!response.ok){setNotice(data.error||"تعذر منح التجربة");return}setContact("");setDisplayName("");setNotice(data.message||"تم منح التجربة");await load()};
  const update=async(id:string,action:"extend_trial"|"update_status",extra:Record<string,unknown>={})=>{setBusy(id);setNotice("");const response=await fetch("/api/admin/subscriptions",{method:"POST",headers,body:JSON.stringify({action,id,...extra})});const data=await response.json().catch(()=>({}));setBusy("");setNotice(response.ok?(data.message||"تم التحديث"):(data.error||"تعذر التحديث"));if(response.ok)await load()};
  const saveBilling=async()=>{setBusy("billing");setNotice("");const response=await fetch("/api/admin/billing-settings",{method:"POST",headers,body:JSON.stringify({provider:billing.provider,mode:billing.mode,publicCheckout:billing.public_checkout==="true",testWebhookEnabled:billing.test_webhook_enabled==="true",livePaymentsEnabled:billing.live_payments_enabled==="true"})});const data=await response.json().catch(()=>({}));setBusy("");setNotice(response.ok?(data.message||"تم حفظ إعدادات الدفع"):(data.error||"تعذر حفظ إعدادات الدفع"));if(response.ok)await load()};
  const recent=useMemo(()=>subscribers.slice(0,20),[subscribers]);const setFlag=(key:"public_checkout"|"test_webhook_enabled"|"live_payments_enabled",value:boolean)=>setBilling(previous=>({...previous,[key]:String(value) as "true"|"false"}));
  return <section className="panel subscription-admin"><div className="panel-head"><div><small>NAVIXA Plus · إدارة محمية</small><h2>إدارة المشتركين والتجارب</h2><p>تبقى صفحات الدفع غير ظاهرة للزوار حتى يقرر المدير فتحها بعد إتمام الاختبارات.</p></div><button onClick={()=>void load()}>تحديث</button></div>{notice&&<p className="admin-inline-notice">{notice}</p>}
    <div className="subscription-summary"><article><small>قائمة الاهتمام</small><b>{summary.waitlist}</b><span>بانتظار دعوة</span></article><article><small>تجارب نشطة</small><b>{summary.trial}</b><span>14 يومًا بلا بطاقة</span></article><article><small>اشتراكات نشطة</small><b>{summary.active}</b><span>من أحداث موثقة فقط</span></article><article><small>تنتهي قريبًا</small><b>{summary.endingSoon}</b><span>خلال 3 أيام</span></article></div>
    <div className="subscription-create"><div><small>دعوة تجريبية يدوية</small><b>منح تجربة Plus لمدة 14 يومًا</b><p>استخدمها فقط للمستخدمين الذين وافقوا على استقبال دعوة التجربة.</p></div><input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="الاسم (اختياري)" aria-label="اسم المشترك"/><input value={contact} onChange={e=>setContact(e.target.value)} placeholder="البريد الإلكتروني" type="email" aria-label="بريد المشترك"/><button disabled={busy==="new"||!contact} onClick={()=>void addTrial()}>{busy==="new"?"جارٍ الحفظ…":"منح التجربة"}</button></div>
    <section className="billing-control" aria-label="إعدادات الدفع"><div className="billing-control-head"><div><small>بوابة الدفع · تحكم إداري</small><h3>الدفع العام مخفي افتراضيًا</h3><p>الوضع الحي لا يمكن تشغيله من دون مفاتيح حيّة وWebhook مستقلين. لا تظهر أي باقة للزوار عند إبقاء خيار الظهور مغلقًا.</p></div><span className={billing.public_checkout==="true"?"billing-state live":"billing-state locked"}>{billing.public_checkout==="true"?"ظاهر للزوار":"مخفي عن الزوار"}</span></div>
      <div className="billing-grid"><label>المزود<select value={billing.provider} onChange={e=>setBilling(previous=>({...previous,provider:e.target.value as "moyasar"}))}><option value="moyasar">Moyasar</option></select></label><label>الوضع<select value={billing.mode} onChange={e=>setBilling(previous=>({...previous,mode:e.target.value as "test"|"live"}))}><option value="test">اختبار آمن</option><option value="live">حي</option></select></label></div>
      <div className="billing-flags"><label><input type="checkbox" checked={billing.test_webhook_enabled==="true"} onChange={e=>setFlag("test_webhook_enabled",e.target.checked)}/><span><b>استقبال أحداث الاختبار</b><small>يسجل الحدث ولا يفعّل اشتراكًا مدفوعًا.</small></span></label><label><input type="checkbox" checked={billing.live_payments_enabled==="true"} onChange={e=>setFlag("live_payments_enabled",e.target.checked)}/><span><b>فتح معالجة الدفع الحي</b><small>يتطلب مفاتيح الحي وتحديد وضع «حي» أولًا.</small></span></label><label><input type="checkbox" checked={billing.public_checkout==="true"} onChange={e=>setFlag("public_checkout",e.target.checked)}/><span><b>إظهار الدفع للزوار</b><small>لن يعمل إلا بعد فتح المعالجة الحية بنجاح.</small></span></label></div>
      <div className="billing-secret-status"><span className={secrets.testKeyConfigured?"ready":"missing"}>مفتاح الاختبار: {secrets.testKeyConfigured?"جاهز":"غير مضاف"}</span><span className={secrets.testWebhookSecretConfigured?"ready":"missing"}>توقيع الاختبار: {secrets.testWebhookSecretConfigured?"جاهز":"غير مضاف"}</span><span className={secrets.liveKeyConfigured?"ready":"missing"}>مفتاح الحي: {secrets.liveKeyConfigured?"جاهز":"غير مضاف"}</span><span className={secrets.liveWebhookSecretConfigured?"ready":"missing"}>توقيع الحي: {secrets.liveWebhookSecretConfigured?"جاهز":"غير مضاف"}</span></div>
      <div className="billing-actions"><button disabled={busy==="billing"} onClick={()=>void saveBilling()}>{busy==="billing"?"جارٍ الحفظ…":"حفظ إعدادات الدفع"}</button><code>/api/billing/webhook</code></div>
      <div className="billing-event-list"><b>آخر أحداث البوابة</b>{events.length?<ul>{events.map(event=><li key={event.id}><span>{event.mode==="live"?"حي":"اختبار"}</span><strong>{event.event_type}</strong><small>{date(event.created_at)}</small></li>)}</ul>:<p>لا توجد أحداث دفع بعد. هذا طبيعي ما دام النظام مقفلًا.</p>}</div>
    </section>
    <div className="subscription-table-wrap"><table><thead><tr><th>المشترك</th><th>الحالة</th><th>الباقة</th><th>تنتهي</th><th>المصدر</th><th>إجراءات</th></tr></thead><tbody>{recent.length?recent.map(item=><tr key={item.id}><td><b>{item.display_name||"—"}</b><small>{item.contact}</small></td><td><span className={`subscriber-status ${item.status}`}>{statusLabel[item.status]}</span></td><td>{planLabel[item.plan]}</td><td>{date(item.status==="trial"?item.trial_ends_at:item.subscription_ends_at)}</td><td>{item.source==="plus_page"?"صفحة Plus":item.source==="admin_trial"?"دعوة إدارية":item.source==="moyasar_webhook"?"Moyasar":"Webhook"}</td><td><div className="subscriber-actions">{item.status!=="trial"&&<button disabled={busy===item.id} onClick={()=>void update(item.id,"extend_trial")}>تجربة 14 يومًا</button>}<select value={`${item.status}:${item.plan}`} disabled={busy===item.id} onChange={e=>{const [status,plan]=e.target.value.split(":");void update(item.id,"update_status",{status,plan})}}><option value="waitlist:trial">قائمة اهتمام</option><option value="trial:trial">تجربة نشطة</option><option value="active:monthly">نشط · شهري</option><option value="active:quarterly">نشط · 3 + 1</option><option value="paused:trial">موقوف</option><option value="cancelled:trial">ملغى</option></select></div></td></tr>):<tr><td colSpan={6} className="subscription-empty">لا توجد طلبات اهتمام أو تجارب بعد. ستظهر هنا الطلبات القادمة من صفحة NAVIXA Plus.</td></tr>}</tbody></table></div>
  </section>;
}
