import { useEffect, useState } from "react";

type Code={id:string;code:string;discount_type:string;discount_value:number;plans:string;max_redemptions:number;redeemed_count:number;reserved_count:number;valid_from:string;valid_until:string;enabled:number};
const headers={"Content-Type":"application/json"};
export default function AdminDiscountCodes(){
  const [codes,setCodes]=useState<Code[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  const [form,setForm]=useState({code:"",discountType:"percent",discountValue:"10",plans:"all",maxRedemptions:"0",validFrom:"",validUntil:""});
  const load=async()=>{const r=await fetch("/api/admin/discount-codes",{cache:"no-store"});if(r.ok){const d=await r.json() as {codes?:Code[]};setCodes(d.codes||[])}};
  useEffect(()=>{void load()},[]);
  const create=async()=>{setBusy(true);setNotice("");const r=await fetch("/api/admin/discount-codes",{method:"POST",headers,body:JSON.stringify(form)});const d=await r.json().catch(()=>({}));setBusy(false);setNotice(r.ok?d.message||"تم إنشاء الكود":d.error||"تعذر إنشاء الكود");if(r.ok){setForm({...form,code:""});await load();}};
  const toggle=async(id:string)=>{const r=await fetch("/api/admin/discount-codes",{method:"POST",headers,body:JSON.stringify({action:"toggle",id})});const d=await r.json().catch(()=>({}));setNotice(r.ok?d.message||"تم التحديث":d.error||"تعذر التحديث");if(r.ok)await load();};
  const founders=async()=>{setBusy(true);setNotice("");const r=await fetch("/api/admin/discount-codes",{method:"POST",headers,body:JSON.stringify({action:"create_founders"})});const d=await r.json().catch(()=>({}));setBusy(false);setNotice(r.ok?d.message||"تم إنشاء عرض المؤسسين":d.error||"تعذر إنشاء عرض المؤسسين");if(r.ok)await load();};
  return <section className="panel discount-codes-admin"><div className="panel-head"><div><small>التسويق والاشتراكات</small><h2>أكواد الخصم</h2><p>أنشئ أكوادًا محددة المدة والباقة، وتابع استخدامها دون حفظ بيانات الدفع.</p></div><div className="discount-head-actions"><button disabled={busy} onClick={()=>void founders()}>عرض المؤسسين: 20% لأول 100</button><button onClick={()=>void load()}>تحديث</button></div></div>{notice&&<p className="admin-inline-notice">{notice}</p>}<div className="discount-code-form"><label>الكود<input value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})} placeholder="NAVIXA20" autoComplete="off" /></label><label>النوع<select value={form.discountType} onChange={e=>setForm({...form,discountType:e.target.value})}><option value="percent">نسبة مئوية</option><option value="fixed">مبلغ ثابت</option></select></label><label>القيمة<input type="number" min="1" value={form.discountValue} onChange={e=>setForm({...form,discountValue:e.target.value})}/></label><label>الباقة<select value={form.plans} onChange={e=>setForm({...form,plans:e.target.value})}><option value="all">كل الباقات</option><option value="monthly">شهري</option><option value="quarterly">ربع سنوي</option></select></label><label>حد الاستخدام<input type="number" min="0" value={form.maxRedemptions} onChange={e=>setForm({...form,maxRedemptions:e.target.value})}/><small>0 = بلا حد</small></label><label>ينتهي في<input type="date" value={form.validUntil} onChange={e=>setForm({...form,validUntil:e.target.value})}/></label><button disabled={busy} onClick={()=>void create()}>{busy?"جارٍ الإنشاء…":"إنشاء كود الخصم"}</button></div><div className="discount-code-list">{codes.length?codes.map(item=><div className="discount-code-row" key={item.id}><b>{item.code}</b><span>{item.discount_type==="percent"?`${item.discount_value}%`:`${item.discount_value} ر.س`}</span><span>{item.plans==="all"?"كل الباقات":item.plans==="monthly"?"شهري":"ربع سنوي"}</span><span>{item.max_redemptions?`${Math.max(0,item.max_redemptions-item.redeemed_count-item.reserved_count)} متبقٍ من ${item.max_redemptions}`:`${item.redeemed_count} استخدامًا`}</span><small>{item.valid_until?`حتى ${item.valid_until}`:"بلا انتهاء"}</small><button onClick={()=>void toggle(item.id)}>{item.enabled?"مفعّل":"متوقف"}</button></div>):<p className="panel-intro">لا توجد أكواد خصم بعد.</p>}</div></section>;
}
