"use client";
import { useEffect, useState } from "react";
import "./usage-analytics.css";

type Account = { email: string; login_count: number; duration_seconds: number; last_login_at: string };
type Feature = { path: string; uses: number; seconds: number };
type Settings = { retentionDays: 7 | 14 | 30 | 60 | 90; alertsEnabled: boolean };
type Alert = { alert_key: string; observed_count: number; window_start: string; status: string; email_sent: number; telegram_sent: number; sent_at: string };
type Data = { summary: { accounts: number; logins: number; minutes: number }; accounts: Account[]; features: Feature[]; settings: Settings; alerts: Alert[] };
const label: Record<string, string> = { "/": "الرئيسية", "/today": "يومي", "/worship": "الورد", "/health": "الصحة", "/meetings": "الاجتماعات" };
const alertLabel: Record<string, string> = { page_views_hour: "فتحات المزايا", tap_events_hour: "تفاعلات الصفحات" };

export default function AdminUsageAnalytics() {
  const [data, setData] = useState<Data | null>(null); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  const load = async () => { const response = await fetch("/api/admin/usage-analytics", { cache: "no-store" }); if (!response.ok) { setNotice("تعذر تحميل تقرير الاستخدام"); return; } setData(await response.json()); };
  useEffect(() => { void load(); }, []);
  const save = async () => { if (!data) return; setSaving(true); const response = await fetch("/api/admin/usage-analytics", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(data.settings) }); const result = await response.json().catch(() => ({})); setSaving(false); setNotice(response.ok ? (result.message || "تم الحفظ") : (result.error || "تعذر الحفظ")); if (response.ok) await load(); };
  return <section className="usage-analytics-admin" aria-label="تحليلات استخدام NAVIXA"><div className="panel-head"><div><small>تحليلات إدارية محمية</small><h2>استخدام NAVIXA</h2><p>لا نسجل نصوص المستخدم أو صوته أو مفاتيحه. الخريطة الحرارية لها قسم مستقل في المراجعة.</p></div><button onClick={() => void load()}>تحديث</button></div>{notice && <p className="admin-inline-notice">{notice}</p>}{data && <><div className="usage-metrics"><article><small>حسابات</small><b>{data.summary.accounts}</b></article><article><small>مرات الدخول</small><b>{data.summary.logins}</b></article><article><small>وقت الاستخدام</small><b>{data.summary.minutes} د</b></article></div><div className="usage-analytics-grid"><section><h3>الخدمات الأكثر استخدامًا</h3>{data.features.length ? <ol>{data.features.map(item => <li key={item.path}><b>{label[item.path] || item.path}</b><span>{item.uses} فتحات · {Math.round(item.seconds / 60)} د</span></li>)}</ol> : <p>ستظهر البيانات بعد استخدام الحسابات للمزايا.</p>}</section><section><h3>تنبيهات الاستخدام الإداري</h3>{data.alerts.length ? <ol>{data.alerts.map((alert, index) => <li key={`${alert.alert_key}-${index}`}><b>{alertLabel[alert.alert_key] || alert.alert_key}</b><span>{alert.observed_count} خلال ساعة · {alert.sent_at ? "تم إبلاغ المدير" : "سجل فقط"}</span></li>)}</ol> : <p>لا توجد تنبيهات غير معتادة مسجلة.</p>}</section></div><section className="usage-settings"><h3>الاحتفاظ والتنبيه</h3><label>مدة الاحتفاظ بإشارات الاستخدام الخام<select value={data.settings.retentionDays} onChange={event => setData(previous => previous ? { ...previous, settings: { ...previous.settings, retentionDays: Number(event.target.value) as Settings["retentionDays"] } } : previous)}>{[7, 14, 30, 60, 90].map(days => <option value={days} key={days}>{days} يومًا</option>)}</select></label><label className="usage-setting-flag"><input type="checkbox" checked={data.settings.alertsEnabled} onChange={event => setData(previous => previous ? { ...previous, settings: { ...previous.settings, alertsEnabled: event.target.checked } } : previous)}/><span><b>تنبيه إداري تلقائي</b><small>يسجل التنبيه في الإدارة ويرسله إلى البريد وTelegram الإداريين عند التهيئة، بحد تكرار 24 ساعة لكل نوع.</small></span></label><button disabled={saving} onClick={() => void save()}>{saving ? "جارٍ الحفظ…" : "حفظ إعدادات التحليلات"}</button></section><section className="usage-accounts"><h3>الحسابات وآخر دخول</h3>{data.accounts.length ? <div>{data.accounts.map(account => <p key={account.email}><b dir="ltr">{account.email}</b><span>{account.login_count} دخول · {Math.round(account.duration_seconds / 60)} د · {account.last_login_at ? new Date(account.last_login_at).toLocaleString("ar-SA") : "—"}</span></p>)}</div> : <p>لا توجد حسابات بعد.</p>}</section></>}</section>;
}
