"use client";

import {useEffect,useMemo,useState} from "react";

type Summary={waitlist:number;trial:number;active:number;endingSoon:number};
type Subscriber={id:string;contact:string;display_name:string;plan:"trial"|"monthly"|"quarterly";status:"waitlist"|"trial"|"active"|"paused"|"cancelled"|"expired";trial_started_at:string;trial_ends_at:string;subscription_ends_at:string;source:string;updated_at:string};
const headers={"Content-Type":"application/json"};
const planLabel:Record<Subscriber["plan"],string>={trial:"تجربة",monthly:"شهري",quarterly:"3 + 1"};
const statusLabel:Record<Subscriber["status"],string>={waitlist:"قائمة اهتمام",trial:"تجربة نشطة",active:"مشترك نشط",paused:"موقوف",cancelled:"ملغى",expired:"منتهي"};
const date=(value:string)=>value?new Intl.DateTimeFormat("ar-SA",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value)):"—";

export default function AdminSubscriptionSettings(){
  const [summary,setSummary]=useState<Summary>({waitlist:0,trial:0,active:0,endingSoon:0});const [subscribers,setSubscribers]=useState<Subscriber[]>([]);const [contact,setContact]=useState("");const [displayName,setDisplayName]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState("");
  const load=async()=>{const response=await fetch("/api/admin/subscriptions",{cache:"no-store"});if(!response.ok)return;const data=await response.json() as {summary:Summary;subscribers:Subscriber[]};setSummary(data.summary);setSubscribers(data.subscribers||[])};
  useEffect(()=>{void load()},[]);
  const addTrial=async()=>{setBusy("new");setNotice("");const response=await fetch("/api/admin/subscriptions",{method:"POST",headers,body:JSON.stringify({action:"create_trial",contact,displayName})});const data=await response.json().catch(()=>({}));setBusy("");if(!response.ok){setNotice(data.error||"تعذر منح التجربة");return}setContact("");setDisplayName("");setNotice(data.message||"تم منح التجربة");await load()};
  const update=async(id:string,action:"extend_trial"|"update_status",extra:Record<string,unknown>={})=>{setBusy(id);setNotice("");const response=await fetch("/api/admin/subscriptions",{method:"POST",headers,body:JSON.stringify({action,id,...extra})});const data=await response.json().catch(()=>({}));setBusy("");setNotice(response.ok?(data.message||"تم التحديث"):(data.error||"تعذر التحديث"));if(response.ok)await load()};
  const recent=useMemo(()=>subscribers.slice(0,20),[subscribers]);
  return <section className="panel subscription-admin"><div className="panel-head"><div><small>NAVIXA Plus · وضع تجريبي</small><h2>إدارة المشتركين والتجارب</h2><p>لا توجد بوابة دفع أو تحصيل مفعل الآن. هذه اللوحة تدير قائمة الاهتمام وتجارب Plus اليدوية فقط.</p></div><button onClick={()=>void load()}>تحديث</button></div>{notice&&<p className="admin-inline-notice">{notice}</p>}
    <div className="subscription-summary"><article><small>قائمة الاهتمام</small><b>{summary.waitlist}</b><span>بانتظار دعوة</span></article><article><small>تجارب نشطة</small><b>{summary.trial}</b><span>14 يومًا بلا بطاقة</span></article><article><small>اشتراكات نشطة</small><b>{summary.active}</b><span>0 حتى تفعيل الدفع</span></article><article><small>تنتهي قريبًا</small><b>{summary.endingSoon}</b><span>خلال 3 أيام</span></article></div>
    <div className="subscription-create"><div><small>دعوة تجريبية يدوية</small><b>منح تجربة Plus لمدة 14 يومًا</b><p>استخدمها فقط للمستخدمين الذين وافقوا على استقبال دعوة التجربة.</p></div><input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="الاسم (اختياري)" aria-label="اسم المشترك"/><input value={contact} onChange={e=>setContact(e.target.value)} placeholder="البريد الإلكتروني" type="email" aria-label="بريد المشترك"/><button disabled={busy==="new"||!contact} onClick={()=>void addTrial()}>{busy==="new"?"جارٍ الحفظ…":"منح التجربة"}</button></div>
    <div className="subscription-table-wrap"><table><thead><tr><th>المشترك</th><th>الحالة</th><th>الباقة</th><th>تنتهي</th><th>المصدر</th><th>إجراءات</th></tr></thead><tbody>{recent.length?recent.map(item=><tr key={item.id}><td><b>{item.display_name||"—"}</b><small>{item.contact}</small></td><td><span className={`subscriber-status ${item.status}`}>{statusLabel[item.status]}</span></td><td>{planLabel[item.plan]}</td><td>{date(item.status==="trial"?item.trial_ends_at:item.subscription_ends_at)}</td><td>{item.source==="plus_page"?"صفحة Plus":item.source==="admin_trial"?"دعوة إدارية":"Webhook"}</td><td><div className="subscriber-actions">{item.status!=="trial"&&<button disabled={busy===item.id} onClick={()=>void update(item.id,"extend_trial")}>تجربة 14 يومًا</button>}<select value={`${item.status}:${item.plan}`} disabled={busy===item.id} onChange={e=>{const [status,plan]=e.target.value.split(":");void update(item.id,"update_status",{status,plan})}}><option value="waitlist:trial">قائمة اهتمام</option><option value="trial:trial">تجربة نشطة</option><option value="active:monthly">نشط · شهري</option><option value="active:quarterly">نشط · 3 + 1</option><option value="paused:trial">موقوف</option><option value="cancelled:trial">ملغى</option></select></div></td></tr>):<tr><td colSpan={6} className="subscription-empty">لا توجد طلبات اهتمام أو تجارب بعد. ستظهر هنا الطلبات القادمة من صفحة NAVIXA Plus.</td></tr>}</tbody></table></div>
    <div className="subscription-gate"><span>◌</span><div><b>حالة بوابة الدفع: مقفلة</b><p>سيبقى Webhook الدفع في وضع الاختبار حتى إضافة مفاتيح Sandbox والتحقق من دورة دفع ناجحة دون تحصيل فعلي.</p></div><code>/api/billing/webhook</code></div>
  </section>;
}
