"use client";
import {useEffect,useState} from "react";

type Settings={feature_enabled:"true"|"false";base_model_enabled:"true"|"false";auto_language_enabled:"true"|"false";global_learning_enabled:"true"|"false";max_file_mb:string;export_pdf_enabled:"true"|"false";export_word_enabled:"true"|"false";tutorial_enabled:"true"|"false";usage_notice_enabled:"true"|"false"};
const initial:Settings={feature_enabled:"true",base_model_enabled:"true",auto_language_enabled:"true",global_learning_enabled:"true",max_file_mb:"250",export_pdf_enabled:"true",export_word_enabled:"true",tutorial_enabled:"true",usage_notice_enabled:"true"};
const headers={"Content-Type":"application/json"};
type GlossaryTerm={id:string;canonical:string;aliases:string[];active:boolean;corrections:number;accepted:number;occurrences:number};

export default function AdminMeetingSettings(){
  const [settings,setSettings]=useState<Settings>(initial),[notice,setNotice]=useState(""),[saving,setSaving]=useState(false),[terms,setTerms]=useState<GlossaryTerm[]>([]);
  const load=async()=>{const response=await fetch("/api/admin/meeting-settings",{cache:"no-store"});if(response.ok){const data=await response.json() as {settings:Settings};setSettings(data.settings||initial)}};
  const loadTerms=async()=>{const response=await fetch("/api/admin/meeting-glossary",{cache:"no-store"});if(response.ok){const data=await response.json() as {terms:GlossaryTerm[]};setTerms(data.terms||[])}};
  useEffect(()=>{void load();void loadTerms()},[]);
  const flag=(key:Exclude<keyof Settings,"max_file_mb">,value:boolean)=>setSettings(current=>({...current,[key]:String(value) as "true"|"false"}));
  const save=async()=>{setSaving(true);setNotice("");const response=await fetch("/api/admin/meeting-settings",{method:"POST",headers,body:JSON.stringify({featureEnabled:settings.feature_enabled==="true",baseModelEnabled:settings.base_model_enabled==="true",autoLanguageEnabled:settings.auto_language_enabled==="true",globalLearningEnabled:settings.global_learning_enabled==="true",maxFileMb:Number(settings.max_file_mb),exportPdfEnabled:settings.export_pdf_enabled==="true",exportWordEnabled:settings.export_word_enabled==="true",tutorialEnabled:settings.tutorial_enabled==="true",usageNoticeEnabled:settings.usage_notice_enabled==="true"})});const data=await response.json().catch(()=>({}));setSaving(false);setNotice(response.ok?(data.message||"تم الحفظ"):(data.error||"تعذر الحفظ"));if(response.ok)await load()};
  const changeTerm=async(id:string,active?:boolean)=>{const response=await fetch(active===undefined?`/api/admin/meeting-glossary?id=${encodeURIComponent(id)}`:"/api/admin/meeting-glossary",active===undefined?{method:"DELETE"}:{method:"POST",headers,body:JSON.stringify({id,active})});setNotice(response.ok?"تم تحديث القاموس العام":"تعذر تحديث المصطلح");if(response.ok)await loadTerms()};
  return <section className="panel subscription-admin"><div className="panel-head"><div><small>محاضراتك واجتماعاتك · إعدادات محمية</small><h2>سياسة «لخّص اجتماعك»</h2><p>هذه اللوحة تتحكم في ظهور الميزة وحدودها فقط. لا يمكنها قراءة صوت المستخدم أو نصه أو ملفاته المحفوظة محليًا.</p></div><button onClick={()=>void load()}>تحديث</button></div>{notice&&<p className="admin-inline-notice">{notice}</p>}
    <div className="billing-flags"><label><input type="checkbox" checked={settings.feature_enabled==="true"} onChange={e=>flag("feature_enabled",e.target.checked)}/><span><b>إظهار ميزة التلخيص</b><small>إيقافها يعرض رسالة صيانة داخل الصفحة ولا يمس جلسات المستخدمين المحفوظة على أجهزتهم.</small></span></label><label><input type="checkbox" checked={settings.base_model_enabled==="true"} onChange={e=>flag("base_model_enabled",e.target.checked)}/><span><b>السماح بالنموذج المتوازن</b><small>يبقى النموذج الخفيف متاحًا؛ المتوازن أدق وأكبر في التنزيل المحلي.</small></span></label><label><input type="checkbox" checked={settings.auto_language_enabled==="true"} onChange={e=>flag("auto_language_enabled",e.target.checked)}/><span><b>السماح باكتشاف اللغة</b><small>للاجتماعات العربية والإنجليزية المختلطة، من دون إرسال الصوت للخادم.</small></span></label><label><input type="checkbox" checked={settings.global_learning_enabled==="true"} onChange={e=>flag("global_learning_enabled",e.target.checked)}/><span><b>السماح بالقاموس العام</b><small>يسمح فقط بمشاركة اختيارية لمصطلحات منقّحة أو متكررة؛ لا يرسل الصوت أو النص الكامل أو عنوان الجلسة.</small></span></label></div>
    <div className="billing-grid"><label>الحد المحلي للملف الصوتي (MB)<select value={settings.max_file_mb} onChange={e=>setSettings(current=>({...current,max_file_mb:e.target.value}))}><option value="100">100 MB</option><option value="250">250 MB</option><option value="500">500 MB</option></select></label></div>
    <div className="billing-flags"><label><input type="checkbox" checked={settings.export_pdf_enabled==="true"} onChange={e=>flag("export_pdf_enabled",e.target.checked)}/><span><b>تصدير PDF</b><small>يحمل شعار NAVIXA والرابط، ويُنشأ من طباعة المتصفح محليًا.</small></span></label><label><input type="checkbox" checked={settings.export_word_enabled==="true"} onChange={e=>flag("export_word_enabled",e.target.checked)}/><span><b>تصدير Word</b><small>يتحمل شعار NAVIXA والرابط، ولا تحمل مكتبته إلا عند الضغط.</small></span></label><label><input type="checkbox" checked={settings.usage_notice_enabled==="true"} onChange={e=>flag("usage_notice_enabled",e.target.checked)}/><span><b>إظهار تنبيه الخصوصية</b><small>يذكّر المستخدم بالحصول على حق التسجيل وموافقة الحاضرين عند الحاجة.</small></span></label></div>
    <div className="billing-grid"><label>القاموس العام المشترك <small>تظهر هنا المصطلحات فقط، بلا صوت أو نص جلسات أو أسماء مستخدمين.</small>{terms.length?<div className="admin-glossary-list">{terms.slice(0,20).map(term=><div key={term.id}><b>{term.canonical}</b><small>{term.aliases.join("، ")||"مصطلح معتمد"} · تصحيحات {term.corrections} · اعتماد {term.accepted}</small><span><button onClick={()=>void changeTerm(term.id,!term.active)}>{term.active?"إيقاف":"تفعيل"}</button><button onClick={()=>void changeTerm(term.id)}>حذف</button></span></div>)}</div>:<small>لا توجد مصطلحات عامة بعد.</small>}</label></div>
    <div className="billing-actions"><button disabled={saving} onClick={()=>void save()}>{saving?"جارٍ الحفظ…":"حفظ سياسة التلخيص"}</button><code>لا توجد تسجيلات أو نصوص أو حسابات مستخدمين في هذا المسار</code></div>
  </section>;
}
