"use client";

import {useEffect,useState} from "react";

type Contribution={id:string;question_text:string;response_text:string;sensitivity:"standard"|"sensitive";created_at:string};
type Pattern={id:string;trigger_text:string;response_text:string;active:number;updated_at:string};
const jsonHeaders={"Content-Type":"application/json"};

export default function AdminAssistantLearningSettings(){
  const [contributions,setContributions]=useState<Contribution[]>([]);const [patterns,setPatterns]=useState<Pattern[]>([]);const [busy,setBusy]=useState("");const [notice,setNotice]=useState("");
  const load=async()=>{const response=await fetch("/api/admin/assistant-learning",{cache:"no-store"});if(!response.ok)return;const data=await response.json() as {contributions:Contribution[];patterns:Pattern[]};setContributions(data.contributions||[]);setPatterns(data.patterns||[])};
  useEffect(()=>{void load()},[]);
  const act=async(action:"approve"|"reject"|"toggle",id:string,extra:Record<string,unknown>={})=>{setBusy(id);setNotice("");const response=await fetch("/api/admin/assistant-learning",{method:"POST",headers:jsonHeaders,body:JSON.stringify({action,id,...extra})});setBusy("");if(!response.ok){setNotice("تعذر حفظ المراجعة");return}setNotice(action==="approve"?"تم اعتماد النمط للردود العامة":"تم تحديث الحالة");await load()};
  const remove=async(id:string)=>{setBusy(id);await fetch(`/api/admin/assistant-learning?id=${encodeURIComponent(id)}`,{method:"DELETE"});setBusy("");setNotice("تم حذف النمط");await load()};
  return <section className="panel assistant-learning-admin"><div className="panel-head"><div><small>التعلّم العالمي الاختياري</small><h2>مراجعة تحسينات المساعد</h2><p>لا تُعرض هنا إلا مساهمات وافق أصحابها على مشاركتها، ولا يعتمد أي رد عام قبل مراجعتك.</p></div><button onClick={()=>void load()}>تحديث</button></div>{notice&&<p className="admin-inline-notice">{notice}</p>}<div className="assistant-review-grid"><div><h3>بانتظار المراجعة <span>{contributions.length}</span></h3>{contributions.length?contributions.map(item=><article className="assistant-review-card" key={item.id}><small>{item.sensitivity==="sensitive"?"موافقة حساسة مستقلة":"مساهمة عامة"}</small><b>يفهم: {item.question_text}</b><p>يرد: {item.response_text}</p><div><button disabled={busy===item.id} onClick={()=>void act("approve",item.id,{trigger:item.question_text,response:item.response_text})}>اعتماد</button><button disabled={busy===item.id} className="quiet" onClick={()=>void act("reject",item.id)}>رفض</button></div></article>):<p className="assistant-empty">لا توجد مساهمات بانتظار المراجعة.</p>}</div><div><h3>الأنماط المعتمدة <span>{patterns.length}</span></h3>{patterns.length?patterns.map(item=><article className="assistant-review-card active" key={item.id}><small>{item.active?"مفعّل":"متوقف"}</small><b>يفهم: {item.trigger_text}</b><p>يرد: {item.response_text}</p><div><button disabled={busy===item.id} className="quiet" onClick={()=>void act("toggle",item.id,{active:!Boolean(item.active)})}>{item.active?"إيقاف":"تفعيل"}</button><button disabled={busy===item.id} className="danger" onClick={()=>void remove(item.id)}>حذف</button></div></article>):<p className="assistant-empty">لن يستخدم المساعد ردودًا عامة حتى تعتمد أول نمط.</p>}</div></div></section>
}
