"use client";

import { useEffect, useMemo, useState } from "react";

type Match={id:string;league:string;home:string;away:string;homeLogo:string;awayLogo:string;kickoff:string;venue:string;venueCity:string};
type Override={matchId:string;hidden:boolean;homeNameAr:string;awayNameAr:string;leagueNameAr:string;homeLogo:string;awayLogo:string;showHomeLogo:boolean;showAwayLogo:boolean};
const arabicDate=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Riyadh"}).format(new Date());
const blank=(matchId:string):Override=>({matchId,hidden:false,homeNameAr:"",awayNameAr:"",leagueNameAr:"",homeLogo:"",awayLogo:"",showHomeLogo:true,showAwayLogo:true});

export default function AdminMatchSettings(){
  const [matches,setMatches]=useState<Match[]>([]);const [overrides,setOverrides]=useState<Record<string,Override>>({});const [selectedId,setSelectedId]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
  const selected=useMemo(()=>matches.find(match=>match.id===selectedId)||null,[matches,selectedId]);
  const draft=selected?overrides[selected.id]||blank(selected.id):null;
  const load=async()=>{setLoading(true);try{const [matchResponse,adminResponse]=await Promise.all([fetch(`/api/matches?date=${arabicDate()}`,{cache:"no-store",credentials:"same-origin"}),fetch("/api/admin/matches",{cache:"no-store",credentials:"same-origin"})]);const matchPayload=await matchResponse.json() as {matches?:Match[]};const adminPayload=await adminResponse.json() as {overrides?:Override[]};const nextMatches=Array.isArray(matchPayload.matches)?matchPayload.matches:[];setMatches(nextMatches);setOverrides(Object.fromEntries((adminPayload.overrides||[]).map(item=>[item.matchId,item])));setSelectedId(current=>nextMatches.some(match=>match.id===current)?current:nextMatches[0]?.id||"");setMessage(nextMatches.length?"تم تحميل مباريات اليوم.":"لا توجد مباريات متاحة اليوم من المصدر.")}catch{setMessage("تعذر تحميل إعدادات المباريات الآن.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const update=(patch:Partial<Override>)=>{if(!draft)return;setOverrides(current=>({...current,[draft.matchId]:{...draft,...patch}}))};
  const save=async()=>{if(!draft)return;setSaving(true);try{const response=await fetch("/api/admin/matches",{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json"},body:JSON.stringify(draft)});if(!response.ok)throw new Error("save");setMessage("تم حفظ تخصيص المباراة. سيظهر في الجدول بعد التحديث القصير.")}catch{setMessage("تعذر حفظ التخصيص. تحقق من جلسة الإدارة.")}finally{setSaving(false)}};
  const remove=async()=>{if(!draft)return;setSaving(true);try{const response=await fetch(`/api/admin/matches?matchId=${encodeURIComponent(draft.matchId)}`,{method:"DELETE",credentials:"same-origin"});if(!response.ok)throw new Error("delete");setOverrides(current=>{const next={...current};delete next[draft.matchId];return next});setMessage("أزيل التخصيص وعادت بيانات المصدر كما هي.")}catch{setMessage("تعذر إزالة التخصيص.")}finally{setSaving(false)}};
  return <section className="admin-match-settings"><div className="admin-match-head"><div><small>تحكم مباشر بالمحتوى الرياضي</small><h3>إدارة المباريات الظاهرة</h3><p>عدّل الاسم العربي أو الشعار، أخفِ مباراة، ثم أعد إظهارها في أي وقت.</p></div><button type="button" onClick={()=>void load()} disabled={loading}>{loading?"جارٍ التحديث…":"تحديث مباريات اليوم"}</button></div><p className="admin-match-message" role="status">{message}</p><div className="admin-match-layout"><div className="admin-match-list">{matches.map(match=>{const item=overrides[match.id];return <button key={match.id} type="button" className={match.id===selectedId?"selected":""} onClick={()=>setSelectedId(match.id)}><span className={item?.hidden?"match-hidden":""}>{item?.hidden?"مخفاة":"ظاهرة"}</span><b>{item?.homeNameAr||match.home} × {item?.awayNameAr||match.away}</b><small>{item?.leagueNameAr||match.league}</small></button>})}{!loading&&!matches.length&&<p>لا توجد مباريات لإدارتها اليوم.</p>}</div>{selected&&draft&&<div className="admin-match-editor"><div className="admin-match-preview"><img src={draft.showHomeLogo?(draft.homeLogo||selected.homeLogo):"/navixa-mark.webp"} alt=""/><b>{draft.homeNameAr||selected.home} × {draft.awayNameAr||selected.away}</b><img src={draft.showAwayLogo?(draft.awayLogo||selected.awayLogo):"/navixa-mark.webp"} alt=""/></div><label>اسم الفريق المضيف بالعربية<input value={draft.homeNameAr} onChange={event=>update({homeNameAr:event.target.value})} placeholder={selected.home}/></label><label>اسم الفريق الضيف بالعربية<input value={draft.awayNameAr} onChange={event=>update({awayNameAr:event.target.value})} placeholder={selected.away}/></label><label>اسم المسابقة بالعربية<input value={draft.leagueNameAr} onChange={event=>update({leagueNameAr:event.target.value})} placeholder={selected.league}/></label><label>رابط شعار المضيف (اختياري)<input type="url" value={draft.homeLogo} onChange={event=>update({homeLogo:event.target.value})} placeholder="https://…"/></label><label>رابط شعار الضيف (اختياري)<input type="url" value={draft.awayLogo} onChange={event=>update({awayLogo:event.target.value})} placeholder="https://…"/></label><div className="admin-match-toggles"><label><input type="checkbox" checked={draft.showHomeLogo} onChange={event=>update({showHomeLogo:event.target.checked})}/> إظهار شعار المضيف</label><label><input type="checkbox" checked={draft.showAwayLogo} onChange={event=>update({showAwayLogo:event.target.checked})}/> إظهار شعار الضيف</label><label><input type="checkbox" checked={!draft.hidden} onChange={event=>update({hidden:!event.target.checked})}/> إظهار المباراة للمستخدمين</label></div><div className="admin-match-actions"><button type="button" onClick={()=>void save()} disabled={saving}>حفظ التعديل</button><button type="button" className="ghost" onClick={()=>void remove()} disabled={saving}>إلغاء التخصيص</button></div><small>الملعب: {selected.venue||"غير معلن"} · المدينة: {selected.venueCity||"غير معلنة"}</small></div>}</div></section>;
}
