"use client";
import {useEffect,useState} from "react";

type Settings={feature_enabled:"true"|"false";base_model_enabled:"true"|"false";auto_language_enabled:"true"|"false";global_learning_enabled:"true"|"false";max_file_mb:string;export_pdf_enabled:"true"|"false";export_word_enabled:"true"|"false";tutorial_enabled:"true"|"false";usage_notice_enabled:"true"|"false"};
type GlossaryTerm={id:string;canonical:string;aliases:string[];active:boolean;corrections:number;accepted:number;occurrences:number};
type Proposal={id:string;canonical:string;aliases:string[];language:string;source:string;count:number;createdAt:string};
const initial:Settings={feature_enabled:"true",base_model_enabled:"true",auto_language_enabled:"true",global_learning_enabled:"true",max_file_mb:"250",export_pdf_enabled:"true",export_word_enabled:"true",tutorial_enabled:"true",usage_notice_enabled:"true"};
const headers={"Content-Type":"application/json"};

export default function AdminMeetingSettings(){
  const [settings,setSettings]=useState<Settings>(initial),[notice,setNotice]=useState(""),[saving,setSaving]=useState(false),[terms,setTerms]=useState<GlossaryTerm[]>([]),[proposals,setProposals]=useState<Proposal[]>([]),[edits,setEdits]=useState<Record<string,{canonical:string;aliases:string}>>({});
  const load=async()=>{const response=await fetch("/api/admin/meeting-settings",{cache:"no-store"});if(response.ok){const data=await response.json() as {settings:Settings};setSettings(data.settings||initial)}};
  const loadGlossary=async()=>{const response=await fetch("/api/admin/meeting-glossary",{cache:"no-store"});if(response.ok){const data=await response.json() as {terms:GlossaryTerm[];proposals:Proposal[]};setTerms(data.terms||[]);setProposals(data.proposals||[])}};
  useEffect(()=>{void load();void loadGlossary()},[]);
  const flag=(key:Exclude<keyof Settings,"max_file_mb">,value:boolean)=>setSettings(current=>({...current,[key]:String(value) as "true"|"false"}));
  const save=async()=>{setSaving(true);setNotice("");const response=await fetch("/api/admin/meeting-settings",{method:"POST",headers,body:JSON.stringify({featureEnabled:settings.feature_enabled==="true",baseModelEnabled:settings.base_model_enabled==="true",autoLanguageEnabled:settings.auto_language_enabled==="true",globalLearningEnabled:settings.global_learning_enabled==="true",maxFileMb:Number(settings.max_file_mb),exportPdfEnabled:settings.export_pdf_enabled==="true",exportWordEnabled:settings.export_word_enabled==="true",tutorialEnabled:settings.tutorial_enabled==="true",usageNoticeEnabled:settings.usage_notice_enabled==="true"})});const data=await response.json().catch(()=>({}));setSaving(false);setNotice(response.ok?(data.message||"تم الحفظ"):(data.error||"تعذر الحفظ"));if(response.ok)await load()};
  const updateTerm=async(id:string,active?:boolean)=>{const response=await fetch(active===undefined?`/api/admin/meeting-glossary?id=${encodeURIComponent(id)}`:"/api/admin/meeting-glossary",active===undefined?{method:"DELETE"}:{method:"POST",headers,body:JSON.stringify({action:"toggle",id,active})});setNotice(response.ok?"تم تحديث القاموس المعتمد":"تعذر تحديث المصطلح");if(response.ok)await loadGlossary()};
  const review=async(proposal:Proposal,action:"approve"|"reject")=>{const edit=edits[proposal.id]||{canonical:proposal.canonical,aliases:proposal.aliases.join("، ")};const response=await fetch("/api/admin/meeting-glossary",{method:"POST",headers,body:JSON.stringify({action,id:proposal.id,canonical:edit.canonical,aliases:edit.aliases.split(/[,،]/).map(value=>value.trim()).filter(Boolean)})});const data=await response.json().catch(()=>({}));setNotice(response.ok?(action==="approve"?"تم اعتماد المصطلح ونشره للقاموس العام":"تم رفض المقترح"):(data.error||"تعذر تحديث المقترح"));if(response.ok)await loadGlossary()};
  const edit=(proposal:Proposal,key:"canonical"|"aliases",value:string)=>setEdits(current=>({...current,[proposal.id]:{canonical:current[proposal.id]?.canonical??proposal.canonical,aliases:current[proposal.id]?.aliases??proposal.aliases.join("، "),[key]:value}}));
  return <section className="panel subscription-admin"><div className="panel-head"><div><small>محاضراتك واجتماعاتك · إعدادات محمية</small><h2>سياسة «لخّص اجتماعك»</h2><p>هذه اللوحة لا تقرأ الصوت أو النص أو عنوان أي جلسة. تصلها المصطلحات القصيرة المنقّحة فقط بعد موافقة المستخدم.</p></div><button onClick={()=>{void load();void loadGlossary()}}>تحديث</button></div>{notice&&<p className="admin-inline-notice">{notice}</p>}
    <div className="billing-flags"><label><input type="checkbox" checked={settings.feature_enabled==="true"} onChange={event=>flag("feature_enabled",event.target.checked)}/><span><b>إظهار ميزة التلخيص</b><small>إيقافها يعرض رسالة صيانة داخل الصفحة ولا يمس جلسات المستخدمين المحفوظة على أجهزتهم.</small></span></label><label><input type="checkbox" checked={settings.base_model_enabled==="true"} onChange={event=>flag("base_model_enabled",event.target.checked)}/><span><b>السماح بالنموذج المتوازن</b><small>يبقى النموذج الخفيف متاحًا؛ المتوازن أدق وأكبر في التنزيل المحلي.</small></span></label><label><input type="checkbox" checked={settings.auto_language_enabled==="true"} onChange={event=>flag("auto_language_enabled",event.target.checked)}/><span><b>السماح باكتشاف اللغة</b><small>للاجتماعات العربية والإنجليزية المختلطة، من دون إرسال الصوت للخادم.</small></span></label><label><input type="checkbox" checked={settings.global_learning_enabled==="true"} onChange={event=>flag("global_learning_enabled",event.target.checked)}/><span><b>استقبال مقترحات القاموس</b><small>يستقبل مقترحات اختيارية للمراجعة؛ لا ينتشر أي مصطلح قبل اعتمادك له.</small></span></label></div>
    <div className="billing-grid"><label>الحد المحلي للملف الصوتي (MB)<select value={settings.max_file_mb} onChange={event=>setSettings(current=>({...current,max_file_mb:event.target.value}))}><option value="100">100 MB</option><option value="250">250 MB</option><option value="500">500 MB</option></select></label></div>
    <div className="billing-flags"><label><input type="checkbox" checked={settings.export_pdf_enabled==="true"} onChange={event=>flag("export_pdf_enabled",event.target.checked)}/><span><b>تصدير PDF</b><small>يحمل شعار NAVIXA والرابط، ويُنشأ من طباعة المتصفح محليًا.</small></span></label><label><input type="checkbox" checked={settings.export_word_enabled==="true"} onChange={event=>flag("export_word_enabled",event.target.checked)}/><span><b>تصدير Word</b><small>يتحمل شعار NAVIXA والرابط، ولا تحمل مكتبته إلا عند الضغط.</small></span></label><label><input type="checkbox" checked={settings.usage_notice_enabled==="true"} onChange={event=>flag("usage_notice_enabled",event.target.checked)}/><span><b>إظهار تنبيه الخصوصية</b><small>يذكّر المستخدم بالحصول على حق التسجيل وموافقة الحاضرين عند الحاجة.</small></span></label></div>
    <div className="billing-grid"><label>مقترحات بانتظار المراجعة <small>راجِع الكتابة البديلة، عدّلها عند الحاجة، ثم اعتمدها أو ارفضها. لا يرى المستخدمون هذه المقترحات قبل الاعتماد.</small>{proposals.length?<div className="admin-glossary-list admin-glossary-proposals">{proposals.map(proposal=>{const value=edits[proposal.id]||{canonical:proposal.canonical,aliases:proposal.aliases.join("، ")};return <div key={proposal.id}><input aria-label="المصطلح المقترح" value={value.canonical} onChange={event=>edit(proposal,"canonical",event.target.value)}/><input aria-label="البدائل المقترحة" value={value.aliases} onChange={event=>edit(proposal,"aliases",event.target.value)}/><small>{proposal.source==="correction"?"تصحيح مستخدم":"نتيجة معتمدة"} · تكرار {proposal.count} · {new Date(proposal.createdAt).toLocaleDateString("ar-SA")}</small><span><button onClick={()=>void review(proposal,"approve")}>اعتماد</button><button onClick={()=>void review(proposal,"reject")}>رفض</button></span></div>})}</div>:<small>لا توجد مقترحات معلقة.</small>}</label></div>
    <div className="billing-grid"><label>القاموس العام المعتمد <small>هذه وحدها هي المصطلحات المتاحة لبقية المستخدمين. يمكنك إيقاف أي مصطلح أو حذفه.</small>{terms.length?<div className="admin-glossary-list">{terms.slice(0,30).map(term=><div key={term.id}><b>{term.canonical}</b><small>{term.aliases.join("، ")||"مصطلح معتمد"} · تصحيحات {term.corrections} · اعتماد {term.accepted}</small><span><button onClick={()=>void updateTerm(term.id,!term.active)}>{term.active?"إيقاف":"تفعيل"}</button><button onClick={()=>void updateTerm(term.id)}>حذف</button></span></div>)}</div>:<small>لا توجد مصطلحات معتمدة بعد.</small>}</label></div>
    <div className="billing-actions"><button disabled={saving} onClick={()=>void save()}>{saving?"جارٍ الحفظ…":"حفظ سياسة التلخيص"}</button><code>لا توجد تسجيلات أو نصوص أو حسابات مستخدمين في هذا المسار</code></div>
  </section>;
}
