import {NextResponse} from "next/server";

type D1Result={meta?:{changes?:number}};
type D1Statement={bind:(...values:unknown[])=>D1Statement;run:()=>Promise<D1Result>;all:<T=Record<string,unknown>>()=>Promise<{results:T[]}>};
type D1Database={prepare:(sql:string)=>D1Statement};
const getDb=async():Promise<D1Database|null>=>{let bound=null;try{bound=(await import("cloudflare:workers") as any).env?.DB||null}catch{};return bound||(globalThis as any).DB||((typeof process!=="undefined"?(process as any).env?.DB:null)||null)};
const validId=(value:unknown)=>typeof value==="string"&&/^[a-zA-Z0-9_-]{24,96}$/.test(value);
async function schema(db:D1Database){await db.prepare("CREATE TABLE IF NOT EXISTS navixa_sync (sync_id TEXT PRIMARY KEY, payload TEXT NOT NULL, updated_at TEXT NOT NULL)").run();}
export async function POST(request:Request){try{const db=await getDb();if(!db)return NextResponse.json({ok:false,configured:false},{status:503});const body=await request.json().catch(()=>({}));const syncId=body?.syncId,payload=typeof body?.payload==="string"?body.payload:"";if(!validId(syncId)||payload.length<2||payload.length>900000)return NextResponse.json({error:"طلب المزامنة غير صالح"},{status:400});await schema(db);await db.prepare("INSERT INTO navixa_sync(sync_id,payload,updated_at) VALUES(?,?,?) ON CONFLICT(sync_id) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at").bind(syncId,payload,new Date().toISOString()).run();return NextResponse.json({ok:true,updatedAt:new Date().toISOString()})}catch{return NextResponse.json({error:"تعذر حفظ المزامنة"},{status:500})}}
export async function GET(request:Request){try{const db=await getDb();if(!db)return NextResponse.json({ok:false,configured:false},{status:503});const syncId=new URL(request.url).searchParams.get("syncId");if(!validId(syncId))return NextResponse.json({error:"رمز المزامنة غير صالح"},{status:400});await schema(db);const result=await db.prepare("SELECT payload,updated_at FROM navixa_sync WHERE sync_id=?").bind(syncId).all<{payload:string;updated_at:string}>();const row=result.results[0];return NextResponse.json({ok:true,found:Boolean(row),payload:row?.payload||null,updatedAt:row?.updated_at||null})}catch{return NextResponse.json({error:"تعذر قراءة المزامنة"},{status:500})}}
export async function DELETE(request:Request){try{const db=await getDb();if(!db)return NextResponse.json({ok:false,configured:false},{status:503});const syncId=new URL(request.url).searchParams.get("syncId");if(!validId(syncId))return NextResponse.json({error:"رمز المزامنة غير صالح"},{status:400});await schema(db);await db.prepare("DELETE FROM navixa_sync WHERE sync_id=?").bind(syncId).run();return NextResponse.json({ok:true})}catch{return NextResponse.json({error:"تعذر حذف المزامنة"},{status:500})}}
