// أزرار NAVIXA الثابتة — العربية
export const arCta = {
  startNow: "ابدأ الآن",
  startFree: "ابدأ مجانًا",
  viewDetails: "عرض التفاصيل",
  openAssistant: "فتح المساعد",
  saveTask: "سجّل المهمة",
  enableAlert: "فعّل التنبيه",
  tryNavixa: "جرّب NAVIXA",
  startWithNavixa: "ابدأ مع NAVIXA",
  watchTutorial: "شاهد الشرح في 25 ثانية",
  setupNameListener: "إعداد نداء الاسم",
  chooseScreenArea: "اختيار شاشة أو منطقة",
  openLocalSummary: "افتح التلخيص المحلي",
  viewDataStorage: "كيف تُحفظ بياناتي؟",
  explorePlans: "استكشف الباقات",
  whatsIncluded: "ماذا يتضمن؟",
  backToHome: "العودة للرئيسية",
  learnMore: "اعرف المزيد",
  close: "إغلاق",
  save: "حفظ",
  cancel: "إلغاء",
} as const;
