// NAVIXA static call-to-action labels — English
export const enCta = {
  startNow: "Start now",
  startFree: "Start free",
  viewDetails: "View details",
  openAssistant: "Open assistant",
  saveTask: "Save task",
  enableAlert: "Enable alert",
  tryNavixa: "Try NAVIXA",
  startWithNavixa: "Start with NAVIXA",
  watchTutorial: "Watch the 25-second guide",
  setupNameListener: "Set up name listening",
  chooseScreenArea: "Choose a screen or area",
  openLocalSummary: "Open local meeting summary",
  viewDataStorage: "How is my data stored?",
  explorePlans: "Explore plans",
  whatsIncluded: "What’s included?",
  backToHome: "Back to home",
  learnMore: "Learn more",
  close: "Close",
  save: "Save",
  cancel: "Cancel",
} as const;
