import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const source=await readFile(new URL("../app/QuranReader.tsx",import.meta.url),"utf8");
assert.match(source,/بندر بليلة/);
assert.match(source,/ياسر الدوسري/);
assert.match(source,/dailyReciter/);
assert.match(source,/surah\.number/);
assert.match(source,/api\/quran-page-audio/);
assert.match(source,/تشغيل تلاوة الصفحة/);
assert.match(source,/activeClip\.end/);
assert.match(source,/source\.get\(ayah\.surah\.number\)/);
assert.doesNotMatch(source,/source\.get\(ayah\.surah\.number\)\?\.\[1\]/);
assert.match(source,/audio\.readyState<1/);
assert.match(source,/audio\.load\(\)/);
assert.match(source,/nextClip\.audioUrl===activeClip\?\.audioUrl/);
assert.match(source,/audio\.currentTime=nextClip\.start/);
assert.match(source,/quran-page-image/);
assert.match(source,/quran-verse-card/);
assert.match(source,/quran-repeat-choices/);
assert.match(source,/تكبير القراءة/);
assert.match(source,/\[1,3,7\]/);
assert.doesNotMatch(source,/SpeechSynthesisUtterance/);
console.log("quran recitation and readable repetition contract: ok");
