// قاموس NAVIXA الرسمي للنصوص الثابتة — العربية
// القاعدة: لا تضع هنا أي اسم مستخدم أو وقت أو مكان أو عدد أو نتيجة أو حالة جلسة.
// هذه القيم تُصاغ داخل المكوّن عبر دوال ديناميكية مستقلة تعتمد على بيانات حقيقية.

export const ar = {
  navixa: {
    name: "NAVIXA",
    tagline: "يفهم يومك",
    dailyAssistant: "مساعدك اليومي",
    beta: "نسخة تجريبية",
  },
  home: {
    welcome: {
      greetingPrefix: "هذا NAVIXA",
      titleLineOne: "مساحتك الذكية",
      titleLineTwo: "ليوم أكثر هدوءًا.",
      intro: "مساعدك اليومي الذي يجمع ما يحتاج انتباهك في مكان واحد، بخصوصية وبإذنك فقط.",
      enter: "ابدأ مع NAVIXA",
      hideForever: "عدم إظهار لوحة الترحيب مرة أخرى على هذا الجهاز",
      permissionAssurance: "لا يبدأ الميكروفون أو مشاركة الشاشة دون موافقتك الصريحة.",
    },
    today: {
      eyebrow: "NAVIXA · يومك الآن",
      title: "هذا ما يحتاج انتباهك اليوم",
      description: "يجمع NAVIXA أهم ما يحدث في يومك في مكان واحد، من نداء اسمك ومتابعة الشاشة إلى الاجتماعات والمهام، وفق ما تسمح له به.",
    },
  },
  tasks: {
    label: "مهامي",
    organization: "تنظيم",
    emptyState: "أضف أول مهمة لليوم",
  },
  notifications: {
    label: "التنبيهات",
    settings: "إعدادات التنبيهات",
    personalReminders: "تذكيراتك الشخصية",
  },
  listener: {
    label: "سماع نداء الاسم",
    readyTitle: "ينبهك عندما يسمع اسمًا يهمك",
    readyDescription: "اكتب الاسم أو الأسماء التي تريد الانتباه لها، ثم فعّل الاستماع عندما تحتاجه.",
    idleStatus: "لا شيء مهم سُمِع حتى الآن",
    permissionNote: "الإذن بيدك دائمًا",
    configure: "إعداد نداء الاسم",
    tutorialTitle: "شاهد كيف يعمل في 25 ثانية",
    tutorialDescription: "أضف الاسم وفعّل التنبيه عندما تحتاجه",
    heardDescription: "التقط NAVIXA الاسم الذي اخترته. افتح التفاصيل لمراجعة ما سُمِع.",
  },
  screenWatch: {
    label: "متابعة الشاشة",
    title: "راقب ما يهمك على الشاشة",
    description: "شارك الشاشة، وحدد الجزء الذي يهمك، ودع NAVIXA ينبهك عند تغير المحتوى أو ظهور النص الذي اخترته.",
    idleStatus: "جاهز للمشاركة",
    privacyNote: "لا تُرفع صور الشاشة",
    configure: "اختيار شاشة أو منطقة",
    tutorialTitle: "شاهد كيف تعمل في 25 ثانية",
    tutorialDescription: "شارك الشاشة وحدد المنطقة التي تهمك",
  },
  productivity: {
    label: "إنتاجيتك",
    focus: "جلسة التركيز",
    ready: "جاهز عندما تبدأ",
    startShortSession: "ابدأ جلسة تركيز قصيرة",
  },
  health: {
    label: "صحتي",
    care: "عنايتك",
  },
  water: {
    label: "ماء اليوم",
    goalReached: "أكملت هدف اليوم",
    reminder: "سجل كوبًا عند كل استراحة",
  },
  worship: {
    label: "عبادتي",
    description: "مواقيت وذكر وقرآن",
  },
  prayer: {
    nextPrayer: "الصلاة القادمة",
    adhan: "الأذان",
    remaining: "المتبقي",
  },
  assistant: {
    label: "المساعد",
    prompt: "اسأل NAVIXA عن يومك أو اطلب منه تلخيص اجتماعك واقتراح الخطوات التالية",
  },
  meetings: {
    label: "لخّص اجتماعك",
    title: "سجّل، فرّغ، وخذ أهم ما حدث معك",
    description: "ابدأ بموافقة واضحة، ثم راجع النص والمهام والقرارات قبل حفظها أو تصديرها.",
    privacyNote: "لا يُرفع صوتك إلى NAVIXA",
    open: "افتح التلخيص المحلي",
    tutorialTitle: "شاهد كيف تعمل في 25 ثانية",
    tutorialDescription: "سجّل وفرّغ وراجع أهم النقاط",
    personal: "محاضراتك واجتماعاتك",
  },
  plus: {
    eyebrow: "NAVIXA PLUS · قريبًا",
    heroFirst: "يومك نفسه،",
    heroEmphasis: "لكن بمساعدة أعمق.",
    heroDescription: "Plus لمن يريد من NAVIXA متابعة أوسع، وتنبيهات أذكى، وتخصيصًا أكبر، مع بقاء الأساسيات اليومية متاحة مجانًا.",
    explorePlans: "استكشف الباقات",
    includedLink: "ماذا يتضمن؟",
    trialTrust: "تجربة 14 يومًا بلا بطاقة",
    noChargeTrust: "لا تحصيل مالي الآن",
    cancellationTrust: "إلغاء واضح عند الإطلاق",
    includedEyebrow: "لمن يريد المزيد من يومه",
    includedTitle: "ماذا يضيف Plus إلى يومك؟",
    includedDescription: "الأساسيات اليومية تبقى متاحة للجميع. Plus يضيف أدوات أوسع ومساعدة أعمق عندما تحتاجها.",
    plansEyebrow: "خطط الإطلاق المقترحة",
    plansTitle: "اختر ما يناسبك لاحقًا",
    plansDescription: "هذه باقات تعريفية في النسخة التجريبية. لن يتم طلب دفع أو بطاقة الآن.",
  },
  privacy: {
    title: "خصوصيتك أولًا",
    description: "لا يبدأ الميكروفون أو مشاركة الشاشة إلا بعد ضغطك وموافقتك. المعالجة الأساسية تتم محليًا في المتصفح.",
    dataLink: "كيف تُحفظ بياناتي؟",
    localAndPrivate: "محلي وخاص",
    dataAndSync: "البيانات والمزامنة",
  },
  community: {
    eyebrow: "NAVIXA COMMUNITY",
    title: "تابع NAVIXA",
    description: "سنعلن الحسابات الرسمية ووسائل الدعم هنا عند اكتمال الهوية الرسمية.",
  },
  general: {
    noCharge: "لا يوجد تحصيل مالي في النسخة التجريبية",
    personalStats: "إحصاءاتك من نشاطك المسجل فقط",
    appearance: "المظهر",
    colorsAndDarkMode: "الألوان والوضع الليلي",
    matches: "مبارياتك",
  },
  account: {
    eyebrow: "دخول آمن بلا كلمة مرور",
    titleFirst: "حسابك يثبت",
    titleEmphasis: "اشتراكك",
    titleLast: "ولا يلمس خصوصيتك.",
    description: "نستخدم رمزًا قصيرًا يصل إلى بريدك، ثم يمكنك تفعيل الدخول السريع ببصمة الجهاز أو Face ID عند توفره.",
    noPassword: "لا كلمة مرور",
    noLocalContent: "لا صوت أو نصوص في الحساب",
    clearLogout: "تسجيل خروج واضح",
  },
} as const;

export type NavixaArabicCopy = typeof ar;
