// NAVIXA Arabic copy source
// عدّل النصوص الثابتة هنا. لا تضع أرقامًا أو أحداثًا غير موثقة؛
// الرسائل الديناميكية تستقبل بياناتها من الواجهة أو التخزين المحلي فقط.

export const ar = {
  brand: {
    name: "NAVIXA",
    tagline: "يفهم يومك",
    dailyAssistant: "مساعدك اليومي",
  },
  home: {
    welcome: {
      greetingPrefix: "هذا NAVIXA",
      titleLineOne: "مساحتك الذكية",
      titleLineTwo: "ليوم أكثر هدوءًا.",
      intro: "مساحتك الهادئة لإنجاز الأهم بخصوصية، وبإذنك فقط.",
      enter: "ابدأ مع NAVIXA",
      hideForever: "عدم إظهار لوحة الترحيب مرة أخرى على هذا الجهاز",
      permissionAssurance: "لا يتم تشغيل الميكروفون أو مشاركة الشاشة دون موافقتك الصريحة.",
    },
    today: {
      eyebrow: "NAVIXA · يومك الآن",
      title: "هذا ما يحتاج انتباهك اليوم",
      description: "NAVIXA يجمع لك ما يهمك في مكان واحد: نداء اسمك، متابعة شاشة، أو تسجيل اجتماع وتلخيصه محليًا بعد إذنك.",
    },
    listener: {
      label: "سماع نداء الاسم",
      readyTitle: "ينبهك عندما يسمع اسمًا يهمك",
      readyDescription: "اكتب اسمًا واحدًا أو عدة أسماء، ثم فعّل الاستماع عندما تحتاجه.",
      idleStatus: "لا شيء مهم سُمع حتى الآن",
      permissionNote: "الإذن بيدك دائمًا",
      configure: "إعداد نداء الاسم",
      tutorialTitle: "شاهد الشرح في 25 ثانية",
      tutorialDescription: "كيف تضيف الاسم وتفعّل التنبيه",
      heardTitle: (name: string) => `تم سماع ${name}`,
      heardDescription: "التقط NAVIXA الاسم الذي اخترته. افتح التفاصيل لمراجعة ما سُمع.",
    },
    screen: {
      label: "متابعة الشاشة",
      title: "راقب شاشة كاملة أو جزءًا ترسمه بنفسك",
      description: "شارك الشاشة، ارسم الإطار الذي يهمك، ودع NAVIXA ينبهك عند تغير المحتوى أو ظهور النص الذي تحدده.",
      idleStatus: "جاهز للمشاركة",
      privacyNote: "لا تُرفع صور الشاشة",
      configure: "اختيار شاشة أو منطقة",
      tutorialTitle: "شاهد الشرح في 25 ثانية",
      tutorialDescription: "كيف تشارك الشاشة وتحدد المنطقة",
    },
    meeting: {
      label: "لخّص اجتماعك",
      title: "سجّل، فرّغ، وخذ أهم النقاط معك",
      description: "ابدأ بموافقة واضحة، ثم راجع النص والمهام والقرارات قبل حفظها أو تصديرها.",
      privacyNote: "لا يُرفع صوتك إلى NAVIXA",
      open: "افتح التلخيص المحلي",
      tutorialTitle: "شاهد الشرح في 25 ثانية",
      tutorialDescription: "كيف تسجّل وتفرّغ وتصدّر",
    },
    privacy: {
      title: "خصوصيتك أولًا",
      description: "لا يبدأ الميكروفون أو مشاركة الشاشة إلا بعد ضغطك وموافقتك. المعالجة الأساسية تتم محليًا في المتصفح.",
      dataLink: "كيف تُحفظ بياناتي؟",
    },
    secondary: {
      productivity: "إنتاجيتك",
      health: "صحتي",
      worship: "عبادتي",
      tasks: "مهامي",
      notifications: "التنبيهات",
      appearance: "المظهر",
      meetings: "محاضراتك واجتماعاتك",
      dataAndSync: "البيانات والمزامنة",
    },
    contact: {
      eyebrow: "NAVIXA COMMUNITY",
      title: "تابع NAVIXA",
      description: "سنعلن الحسابات الرسمية ووسائل الدعم هنا عند اكتمال الهوية الرسمية.",
    },
    trust: {
      microphone: "لا يبدأ الميكروفون دون موافقتك",
      screen: "لا تُرفع لقطات الشاشة إلى NAVIXA",
      noCharge: "لا يوجد تحصيل مالي في النسخة التجريبية",
      personalStats: "إحصاءاتك من نشاطك المسجل فقط",
    },
  },
  plus: {
    eyebrow: "NAVIXA PLUS · قريبًا",
    heroFirst: "يومك نفسه،",
    heroEmphasis: "لكن بعمق أكبر.",
    heroDescription: "Plus هي الطبقة الاختيارية لمن يريد من NAVIXA مساعدًا أذكى وتخصيصًا أوسع، من دون المساس بالأساسيات اليومية المجانية.",
    explorePlans: "استكشف الباقات",
    includedLink: "ماذا يتضمن؟",
    trialTrust: "تجربة 14 يومًا بلا بطاقة",
    noChargeTrust: "لا تحصيل مالي الآن",
    cancellationTrust: "إلغاء واضح عند الإطلاق",
    includedEyebrow: "مصمم لمن يريد المزيد",
    includedTitle: "ماذا ستحصل عليه في Plus؟",
    includedDescription: "الأدوات اليومية الأساسية تبقى متاحة للجميع. Plus يمنحك راحة أكثر وذكاء أعمق.",
    plansEyebrow: "خطط الإطلاق المقترحة",
    plansTitle: "اختر ما يناسبك لاحقًا",
    plansDescription: "هذه باقات تعريفية في النسخة التجريبية. لن يتم طلب دفع أو بطاقة الآن.",
  },
  account: {
    eyebrow: "دخول آمن بلا كلمة مرور",
    titleFirst: "حسابك يثبت",
    titleEmphasis: "اشتراكك",
    titleLast: "ولا يلمس خصوصيتك.",
    description: "نستخدم رمزًا قصيرًا يصل إلى بريدك، ثم يمكنك تفعيل الدخول السريع ببصمة الجهاز أو Face ID عند توفره.",
    noPassword: "لا كلمة مرور",
    noLocalContent: "لا صوت أو نصوص في الحساب",
    clearLogout: "تسجيل خروج واضح",
  },
} as const;
