// NAVIXA official copy dictionary — English
// Static copy only. Names, times, places, counts, results, and live states
// must be composed in component-level dynamic formatter functions.

export const en = {
  navixa: {
    name: "NAVIXA",
    tagline: "Understands your day",
    dailyAssistant: "Your daily assistant",
    beta: "Beta",
  },
  home: {
    welcome: {
      greetingPrefix: "this is NAVIXA",
      titleLineOne: "Your smart space",
      titleLineTwo: "for a calmer day.",
      intro: "A calm space for what matters, with privacy and only with your permission.",
      enter: "Start with NAVIXA",
      hideForever: "Do not show this welcome screen again on this device",
      permissionAssurance: "The microphone and screen sharing never start without your explicit permission.",
    },
    today: {
      eyebrow: "NAVIXA · Today",
      title: "What needs your attention today",
      description: "NAVIXA brings what matters into one place: name alerts, screen monitoring, or local meeting recording and summarisation with your permission.",
    },
  },
  tasks: {
    label: "My tasks",
    organization: "Organise",
    emptyState: "Add your first task today",
  },
  notifications: {
    label: "Notifications",
    settings: "Your settings",
    personalReminders: "Your personal reminders",
  },
  listener: {
    label: "Name listener",
    readyTitle: "Alerts you when it hears a name that matters",
    readyDescription: "Add one or more names, then turn on listening whenever you need it.",
    idleStatus: "Nothing important has been heard yet",
    permissionNote: "You are always in control of permission",
    configure: "Set up name listening",
    tutorialTitle: "Watch the 25-second guide",
    tutorialDescription: "How to add a name and enable alerts",
    heardDescription: "NAVIXA detected the name you selected. Open the details to review what was heard.",
  },
  screenWatch: {
    label: "Screen watch",
    title: "Monitor a full screen or draw your own area",
    description: "Share your screen, draw the area that matters, and let NAVIXA alert you when content changes or selected text appears.",
    idleStatus: "Ready to share",
    privacyNote: "Screen images are not uploaded to NAVIXA",
    configure: "Choose a screen or area",
    tutorialTitle: "Watch the 25-second guide",
    tutorialDescription: "How to share a screen and choose an area",
  },
  productivity: {
    label: "Productivity",
    focus: "Focus session",
    ready: "Ready when you are",
    startShortSession: "Start a short focus session",
  },
  health: {
    label: "My health",
    care: "Your care",
  },
  water: {
    label: "Water today",
    goalReached: "You reached today’s goal",
    reminder: "Log a cup at every break",
  },
  worship: {
    label: "My worship",
    description: "Prayer times, remembrance, and Quran",
  },
  prayer: {
    nextPrayer: "Next prayer",
    adhan: "Adhan",
    remaining: "Remaining",
  },
  assistant: {
    label: "Assistant",
    prompt: "Summarise the meeting points and suggest the next actions",
  },
  meetings: {
    label: "Summarise your meeting",
    title: "Record, transcribe, and take the key points with you",
    description: "Start with clear consent, then review the transcript, tasks, and decisions before saving or exporting.",
    privacyNote: "Your audio is not uploaded to NAVIXA",
    open: "Open local meeting summary",
    tutorialTitle: "Watch the 25-second guide",
    tutorialDescription: "How to record, transcribe, and export",
    personal: "Your lectures and meetings",
  },
  plus: {
    eyebrow: "NAVIXA PLUS · Coming soon",
    heroFirst: "Your same day,",
    heroEmphasis: "with more depth.",
    heroDescription: "Plus is the optional layer for people who want a smarter NAVIXA and deeper customisation, without affecting the free daily essentials.",
    explorePlans: "Explore plans",
    includedLink: "What’s included?",
    trialTrust: "14-day trial, no card",
    noChargeTrust: "No charge right now",
    cancellationTrust: "Clear cancellation at launch",
    includedEyebrow: "Designed for people who want more",
    includedTitle: "What will you get with Plus?",
    includedDescription: "The core daily tools remain available to everyone. Plus offers more ease and deeper intelligence.",
    plansEyebrow: "Proposed launch plans",
    plansTitle: "Choose what suits you later",
    plansDescription: "These are introductory beta plans. No payment or card will be requested now.",
  },
  privacy: {
    title: "Privacy first",
    description: "The microphone and screen sharing only begin after your action and permission. Core processing happens locally in the browser.",
    dataLink: "How is my data stored?",
    localAndPrivate: "Local and private",
    dataAndSync: "Data and sync",
  },
  community: {
    eyebrow: "NAVIXA COMMUNITY",
    title: "Follow NAVIXA",
    description: "Official accounts and support channels will be announced here once the brand identity is complete.",
  },
  general: {
    noCharge: "No charge in the beta version",
    personalStats: "Your stats come from your recorded activity only",
    appearance: "Appearance",
    colorsAndDarkMode: "Colours and dark mode",
    matches: "Your matches",
  },
  account: {
    eyebrow: "Secure passwordless access",
    titleFirst: "Your account proves",
    titleEmphasis: "your subscription",
    titleLast: "without touching your privacy.",
    description: "We use a short code sent to your email, then you can enable quick access with your device biometrics or Face ID when available.",
    noPassword: "No password",
    noLocalContent: "No audio or transcripts in your account",
    clearLogout: "Clear sign out",
  },
} as const;

export type NavixaEnglishCopy = typeof en;
