"use client";
import {FormEvent,PointerEvent,useEffect,useRef,useState} from "react";
import "./floating-assistant.css";
import "./assistant-limit.css";
type Message={from:"user"|"navixa";text:string};
const MAX=20,LIMIT=3,today=()=>new Date().toISOString().slice(0,10);
export default function FloatingAssistant({onAddTask}:{onAddTask:(title:string)=>void}){
 const [open,setOpen]=useState(false),[messages,setMessages]=useState<Message[]>([{from:"navixa",text:"هلا، كيف أقدر أساعدك؟"}]),[pos,setPos]=useState({x:24,y:0}),[clears,setClears]=useState(0);const drag=useRef<{x:number;y:number;left:number;top:number}|null>(null);
 useEffect(()=>{document.documentElement.classList.toggle("assistant-off",localStorage.getItem("navixa-assistant-enabled")==="false");setPos(p=>({...p,y:Math.max(90,innerHeight-108)}));try{const saved=JSON.parse(localStorage.getItem("navixa-chat")||"[]");if(saved.length)setMessages(saved);const u=JSON.parse(localStorage.getItem("navixa-chat-clears")||"{}");setClears(u.date===today()?u.count:0)}catch{}},[]);useEffect(()=>localStorage.setItem("navixa-chat",JSON.stringify(messages.slice(-MAX))),[messages]);
 const down=(e:PointerEvent<HTMLButtonElement>)=>{drag.current={x:e.clientX,y:e.clientY,left:pos.x,top:pos.y};e.currentTarget.setPointerCapture(e.pointerId)},move=(e:PointerEvent<HTMLButtonElement>)=>{if(drag.current)setPos({x:Math.max(10,Math.min(innerWidth-76,drag.current.left+e.clientX-drag.current.x)),y:Math.max(72,Math.min(innerHeight-76,drag.current.top+e.clientY-drag.current.y))})};
 const reply=(text:string)=>setTimeout(()=>setMessages(m=>[...m,{from:"navixa",text}]),240);const saveRequest=(text:string)=>{const key="navixa-development-requests",items=JSON.parse(localStorage.getItem(key)||"[]");items.push({text,createdAt:new Date().toISOString(),status:"جديد"});localStorage.setItem(key,JSON.stringify(items.slice(-100)))};
 const understand=(raw:string)=>{const t=raw.replace(/[؟?!،,.]/g," ").replace(/\s+/g," ").trim();if(/^(هلا|هلو|السلام|سلام|مرحبا|صباح الخير|مساء الخير|كيف الحال|كيفك|شلونك|اخبارك)/.test(t))return reply(/كيف الحال|كيفك|شلونك|اخبارك/.test(t)?"بخير دامك بخير 😄 وش عندك اليوم؟":"ياهلا فيك 😄 وش تبي نضبط؟");if(/(شكرا|مشكور|يعطيك العافية|تسلم)/.test(t))return reply("العفو، بالخدمة دائمًا 🙌");if(/(نكتة|ضحكني|طفشان|طقطقة)/.test(t))return reply("أبشر 😄 الموظف قال: بأخذ بريك خمس دقايق… رجع بعد الإجازة السنوية!");if(/(صحتي|الكاميرا|الجلوس|الماء|تمرين|وضعية)/.test(t)){reply("فتحت لك مركز صحتي؛ هناك كل الأدوات المطلوبة.");return setTimeout(()=>location.href="/health",650)}if(/(تركيز|بومودورو|25 دقيقة)/.test(t)){reply("وصلتك إلى جلسة التركيز.");location.hash="focus";return}if(/(مراقبة الشاشة|شارك الشاشة|متابعة الشاشة|الاستماع|اسمع اسمي|راقب اسمي)/.test(t)){reply("فتحت لك أداة المتابعة، وتشغيلها يبدأ بعد موافقتك.");location.hash="assistant";return}if(/(مهمة|ذكرني|موعد|اجتماع|مقابلة|كويز|اختبار|فاينل|نهائي|تسليم|ددلاين|لازم|عندي)/.test(t)){const type=/اجتماع|مقابلة/.test(t)?"موعد":/كويز|اختبار|فاينل|نهائي/.test(t)?"اختبار":/تسليم|ددلاين/.test(t)?"تسليم":"مهمة";onAddTask(t);return reply(`تمام، فهمتها كـ${type} وأضفتها مباشرة.`)}if(/(أنشئ|انشئ|اصنع|ابني|سو لي|سوي لي|أضف ميزة|دعم)/.test(t)){saveRequest(t);return reply("هذا الطلب غير موجود حاليًا. حفظته ضمن طلبات التطوير حتى نضيفه أو نوسّع دعمه.")}if(/(تعبان|متضايق|زعلان|مضغوط|طفشت)/.test(t))return reply("يا ساتر، واضح اليوم ضاغط عليك 😅 قل لي وش صار، ونفكك الموضوع بهدوء.");reply("فهمت عليك بشكل عام، لكن أبي أحدد المطلوب: تبيه مهمة، موعد، أو تعديل في الموقع؟")};
 const send=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const input=e.currentTarget.elements.namedItem("message") as HTMLInputElement,text=input.value.trim();if(!text)return;input.value="";setMessages(m=>[...m,{from:"user",text}]);understand(text)};const clear=()=>{if(clears>=LIMIT)return;const n=clears+1;setClears(n);localStorage.setItem("navixa-chat-clears",JSON.stringify({date:today(),count:n}));setMessages([{from:"navixa",text:"بدأنا من جديد. وش تبي ننجز؟"}])},long=messages.length>=MAX;
 return <div className="floating-assistant" style={{left:pos.x,top:pos.y}} dir="rtl">{open&&<section className="assistant-panel"><header><div><img className="assistant-logo-mark" src="/navixa-mark.png" alt="" /><span><b>NAVIXA</b><small>متصل الآن</small></span></div><button onClick={()=>setOpen(false)}>×</button></header><div className="assistant-chat">{messages.slice(-MAX).map((m,i)=><p key={i} className={m.from}>{m.text}</p>)}{long&&<aside className="chat-limit"><b>المحادثة صارت طويلة</b><span>ابدأ من الصفر لتبقى التجربة سريعة.</span><button disabled={clears>=LIMIT} onClick={clear}>{clears>=LIMIT?"استخدمت حد الحذف اليومي":`حذف المحادثة (${LIMIT-clears} متبقية)`}</button></aside>}</div><form onSubmit={send}><input name="message" disabled={long} placeholder={long?"ابدأ محادثة جديدة أولًا":"اكتب رسالتك..."}/><button disabled={long}>↑</button></form></section>}<button className="assistant-bubble" aria-label="فتح مساعد NAVIXA" onClick={()=>setOpen(v=>!v)} onPointerDown={down} onPointerMove={move} onPointerUp={()=>drag.current=null}><span className="mini-mark"><img src="/navixa-mark.png" alt="" /></span><em>متاح</em></button></div>
}
