"use client";
import {useEffect,useRef,useState} from "react";
import {FilesetResolver,PoseLandmarker} from "@mediapipe/tasks-vision";
import "./health.css";
import "./exercise-motion.css";

type Posture="idle"|"loading"|"good"|"care"|"missing";
const format=(v:number)=>`${String(Math.floor(v/3600)).padStart(2,"0")}:${String(Math.floor(v%3600/60)).padStart(2,"0")}:${String(v%60).padStart(2,"0")}`;
const exercises=[{name:"تمدد الذراعين",title:"ارفع ذراعيك بهدوء",steps:["قف وظهرك مستقيم.","ارفع الذراعين للأعلى ببطء.","تنفس بعمق ثم اخفضهما."],motion:"arms"},{name:"إرخاء الكتفين",title:"حرّك كتفيك للخلف",steps:["أرخِ ذراعيك بجانبك.","دوّر الكتفين للخلف ببطء.","كرر الحركة خمس مرات."],motion:"shoulders"},{name:"تمدد جانبي",title:"مل بجسمك إلى الجانبين",steps:["ثبت قدميك على الأرض.","ارفع ذراعًا ومل للجانب.","بدّل الجهة بدون استعجال."],motion:"side"},{name:"إراحة الرقبة",title:"حرّك رقبتك بلطف",steps:["أبقِ الكتفين مرتخيين.","مل الرأس يمينًا ثم يسارًا.","توقف فورًا إذا شعرت بألم."],motion:"neck"}];

export default function HealthMonitor(){
  const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),pose=useRef<PoseLandmarker|null>(null),frame=useRef<number|null>(null),lastVideo=useRef(-1),goodFrames=useRef(0),careFrames=useRef(0),lastBreak=useRef(0),lastWater=useRef(0);
  const [monitoring,setMonitoring]=useState(false),[posture,setPosture]=useState<Posture>("idle"),[seconds,setSeconds]=useState(0),[breakMinutes,setBreakMinutes]=useState(30),[waterMinutes,setWaterMinutes]=useState(60),[cups,setCups]=useState(0),[message,setMessage]=useState("جاهز لبدء جلسة صحية"),[exercise,setExercise]=useState(false),[exerciseIndex,setExerciseIndex]=useState(0);
  const today=()=>new Date().toISOString().slice(0,10);
  useEffect(()=>{setSeconds(Number(localStorage.getItem(`navixa-sitting-${today()}`)||0));setCups(Number(localStorage.getItem(`navixa-water-${today()}`)||0))},[]);
  useEffect(()=>()=>stop(false),[]);
  const notify=(title:string,body:string)=>{if("Notification" in window&&Notification.permission==="granted")new Notification(title,{body})};
  useEffect(()=>{if(!monitoring)return;const timer=window.setInterval(()=>setSeconds(current=>{const next=current+1;localStorage.setItem(`navixa-sitting-${today()}`,String(next));const moveAt=breakMinutes*60;if(next>=moveAt&&next%moveAt===0&&lastBreak.current!==next){lastBreak.current=next;setMessage("حان وقت الحركة — دقيقة واحدة تكفي");setExercise(true);notify("وقت الحركة","انهض بهدوء ومدد كتفيك لدقيقة")}const drinkAt=waterMinutes*60;if(next>=drinkAt&&next%drinkAt===0&&lastWater.current!==next){lastWater.current=next;notify("تذكير الماء","خذ كوب ماء وحافظ على نشاطك")}return next}),1000);return()=>clearInterval(timer)},[monitoring,breakMinutes,waterMinutes]);
  const analyse=()=>{if(!video.current||!pose.current||!stream.current)return;if(video.current.readyState>=2&&video.current.currentTime!==lastVideo.current){lastVideo.current=video.current.currentTime;const points=pose.current.detectForVideo(video.current,performance.now()).landmarks[0];if(!points){setPosture("missing");setMessage("الصورة غير واضحة — نظّف عدسة الكاميرا، حسّن الإضاءة واقترب قليلًا")}else{const le=points[7],re=points[8],ls=points[11],rs=points[12],width=Math.max(Math.abs(ls.x-rs.x),.05),height=((ls.y+rs.y)/2-(le.y+re.y)/2)/width,tilt=Math.abs(ls.y-rs.y)/width,isGood=height>.34&&tilt<.18;if(isGood){goodFrames.current++;careFrames.current=0;if(goodFrames.current>8){setPosture("good");setMessage("وضعيتك متوازنة — استمر")}}else{careFrames.current++;goodFrames.current=0;if(careFrames.current>12){setPosture("care");setMessage("ارفع رأسك وأرخِ كتفيك قليلًا")}}}}frame.current=requestAnimationFrame(analyse)};
  const start=async()=>{try{setPosture("loading");setMessage("نجهّز التحليل المحلي…");const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:640},height:{ideal:480}},audio:false});stream.current=media;if(video.current){video.current.srcObject=media;await video.current.play()}const vision=await FilesetResolver.forVisionTasks("/mediapipe");try{pose.current=await PoseLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:"/mediapipe/pose_landmarker_lite.task",delegate:"GPU"},runningMode:"VIDEO",numPoses:1})}catch{pose.current=await PoseLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:"/mediapipe/pose_landmarker_lite.task",delegate:"CPU"},runningMode:"VIDEO",numPoses:1})}setMonitoring(true);setPosture("good");setMessage("المراقبة تعمل داخل جهازك فقط");if("Notification" in window&&Notification.permission==="default")void Notification.requestPermission();analyse()}catch{stop(false);setPosture("idle");setMessage("تعذر تشغيل الكاميرا — تحقق من الصلاحية")}};
  const stop=(show=true)=>{if(frame.current)cancelAnimationFrame(frame.current);frame.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;pose.current?.close();pose.current=null;setMonitoring(false);setPosture("idle");if(show)setMessage("توقفت الكاميرا والمراقبة فورًا")};
  const addWater=()=>{const next=cups+1;setCups(next);localStorage.setItem(`navixa-water-${today()}`,String(next));setMessage("صحة وعافية — تم تسجيل كوب ماء")};
  return <section className="health-monitor" id="health" aria-labelledby="health-title">
    <div className="health-heading"><div><small>صحة NAVIXA</small><h2 id="health-title">اجلس بوعي، وتحرك في وقتك</h2><p>تحليل وضعيتك يتم محليًا في المتصفح ولا تُرفع أو تُحفظ صور الكاميرا.</p></div><button className="health-emergency" onClick={()=>stop()}>■ إيقاف فوري</button></div>
    <div className="health-layout"><article className="posture-panel"><div className="posture-top"><div><small>مراقبة وضعية الجلوس</small><h3>{monitoring?"جلسة نشطة":"الكاميرا متوقفة"}</h3></div><span className={`posture-dot ${posture}`}>{posture==="good"?"وضعية جيدة":posture==="care"?"تحتاج تعديل":posture==="loading"?"جارٍ التحضير":posture==="missing"?"الصورة غير واضحة":"خصوصية مفعّلة"}</span></div><div className="health-video"><video ref={video} muted playsInline/>{!monitoring&&<div className="video-placeholder"><span>📷</span><b>لن تعمل الكاميرا إلا بموافقتك</b><small>الفيديو يبقى داخل جهازك</small></div>}{monitoring&&<i className="health-scan"/>}</div><div className="posture-message"><span className={posture}/><p><b>{message}</b><small>ضع الكاميرا أمامك ليظهر الرأس والكتفان بوضوح.</small></p></div><div className="health-buttons">{!monitoring?<button onClick={start}>📷 تفعيل الكاميرا والمراقبة</button>:<button className="stop" onClick={()=>stop()}>إنهاء الجلسة</button>}<button className="ghost" onClick={()=>{setSeconds(0);localStorage.setItem(`navixa-sitting-${today()}`,"0")}}>تصفير مدة اليوم</button></div></article>
      <aside className="health-side"><article className="sitting-card"><small>مدة جلوسك اليوم</small><b>{format(seconds)}</b><span><i style={{width:`${Math.min(100,seconds/(breakMinutes*60)*100)}%`}}/></span><p>تنبيه الحركة كل <select aria-label="مدة تذكير الحركة" value={breakMinutes} onChange={e=>setBreakMinutes(Number(e.target.value))}><option value="20">20 دقيقة</option><option value="30">30 دقيقة</option><option value="45">45 دقيقة</option><option value="60">60 دقيقة</option></select></p></article><article className="water-health"><div><span>◌</span><p><small>الماء اليوم</small><b>{cups} أكواب</b></p></div><button onClick={addWater}>شربت كوبًا</button><label>ذكّرني كل <select value={waterMinutes} onChange={e=>setWaterMinutes(Number(e.target.value))}><option value="30">30 دقيقة</option><option value="60">60 دقيقة</option><option value="90">90 دقيقة</option></select></label></article><article className="exercise-card"><span>↗</span><div><small>تمرين سريع</small><b>تمدد الكتفين والظهر</b><p>60 ثانية، بدون معدات.</p></div><button onClick={()=>setExercise(true)}>ابدأ</button></article><article className="privacy-health"><span>✓</span><div><b>خصوصية واضحة</b><p>النموذج والكاميرا يعملان محليًا. زر الإيقاف يقطع الكاميرا فورًا.</p></div></article></aside></div>
    {exercise&&<div className="exercise-modal" onClick={()=>setExercise(false)}><article onClick={e=>e.stopPropagation()}><button aria-label="إغلاق التمرين" onClick={()=>setExercise(false)}>×</button><small>تمرين {exerciseIndex+1} من {exercises.length}</small><h3>{exercises[exerciseIndex].title}</h3><div className={`stretch-figure ${exercises[exerciseIndex].motion}`} aria-label={`صورة متحركة توضح ${exercises[exerciseIndex].name}`}><span/><i/><b/><em/></div><ol>{exercises[exerciseIndex].steps.map(step=><li key={step}>{step}</li>)}</ol><button className="done" onClick={()=>{if(exerciseIndex<exercises.length-1){setExerciseIndex(i=>i+1);setMessage("ممتاز — انتقلنا للتمرين التالي")}else{setExercise(false);setExerciseIndex(0);setMessage("أحسنت — أكملت سلسلة التمارين")}}}>{exerciseIndex<exercises.length-1?"تم التمرين — التالي":"تمت كل التمارين"}</button></article></div>}
  </section>
}
