"use client";
import {useEffect,useRef,useState} from "react";
import {FilesetResolver,PoseLandmarker} from "@mediapipe/tasks-vision";
import {isScreenEnabled,sendTelegramAlert} from "./alertPrefs";
import EyeRestClock from "./EyeRestClock";
import BreathingExercise from "./BreathingExercise";
import "./health.css";
import "./exercise-motion.css";

type Posture="idle"|"loading"|"good"|"care"|"missing";
const format=(v:number)=>`${String(Math.floor(v/3600)).padStart(2,"0")}:${String(Math.floor(v%3600/60)).padStart(2,"0")}:${String(v%60).padStart(2,"0")}`;
const exercises=[{name:"تمدد الذراعين",title:"تمدد الصدر والذراعين",duration:30,focus:"فتح الصدر وتحسين التنفس",steps:["اجلس أو قف وظهرك مستقيم.","شبّك يديك خلف ظهرك وافتح صدرك.","اثبت 10 ثوانٍ مع تنفس هادئ ثم أرخِ الحركة."],motion:"arms"},{name:"إرخاء الكتفين",title:"دوائر الكتفين الهادئة",duration:30,focus:"تخفيف شدّ الرقبة والكتفين",steps:["أنزل كتفيك بعيدًا عن أذنيك.","حرّك الكتفين للخلف في دوائر بطيئة.","كرر 5 مرات ثم اعكس الاتجاه."],motion:"shoulders"},{name:"تمدد جانبي",title:"تمدد جانبي واقف",duration:30,focus:"إطالة الجانبين بدون ضغط",steps:["ثبت قدميك بعرض الحوض.","ارفع ذراعًا ومل للجانب حتى تشعر بتمدد لطيف.","بدّل الجهة وحافظ على تنفسك منتظمًا."],motion:"side"},{name:"إراحة الرقبة",title:"حركة الرقبة الآمنة",duration:30,focus:"إراحة الرقبة من وضعية الشاشة",steps:["أبقِ الذقن موازيًا للأرض.","مل الرأس يمينًا ويسارًا بمدى مريح.","لا تدفع الرأس ولا تستمر مع وجود ألم."],motion:"neck"}];

export default function HealthMonitor(){
  const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),pose=useRef<PoseLandmarker|null>(null),frame=useRef<number|null>(null),lifecycle=useRef(0),lastVideo=useRef(-1),goodFrames=useRef(0),careFrames=useRef(0),lastBreak=useRef(0),lastWater=useRef(0);
  const [monitoring,setMonitoring]=useState(false),[posture,setPosture]=useState<Posture>("idle"),[seconds,setSeconds]=useState(0),[breakMinutes,setBreakMinutes]=useState(30),[waterMinutes,setWaterMinutes]=useState(60),[cups,setCups]=useState(0),[lastWaterAt,setLastWaterAt]=useState<string|null>(null),[sessionAlert,setSessionAlert]=useState<string|null>(null),[privacyNotice,setPrivacyNotice]=useState(false),[message,setMessage]=useState("جاهز لبدء جلسة صحية"),[exercise,setExercise]=useState(false),[exerciseIndex,setExerciseIndex]=useState(0),[exerciseSeconds,setExerciseSeconds]=useState(30);
  useEffect(()=>{if(!exercise)return;const timer=window.setInterval(()=>setExerciseSeconds(s=>{if(s<=1)return 0;return s-1}),1000);return()=>window.clearInterval(timer)},[exercise]);
  const startExercise=()=>{setExerciseIndex(0);setExerciseSeconds(exercises[0].duration);setExercise(true)};
  const today=()=>new Date().toISOString().slice(0,10);
  useEffect(()=>{const waterKey=`navixa-water-${today()}`;setSeconds(Number(localStorage.getItem(`navixa-sitting-${today()}`)||0));setCups(Number(localStorage.getItem(waterKey)||0));setLastWaterAt(localStorage.getItem(`${waterKey}-last`))},[]);
  const notify=(title:string,body:string)=>{if("Notification" in window&&Notification.permission==="granted")new Notification(title,{body})};
  useEffect(()=>{if(!monitoring)return;const timer=window.setInterval(()=>setSeconds(current=>{const next=current+1;localStorage.setItem(`navixa-sitting-${today()}`,String(next));const moveAt=breakMinutes*60;if(next>=moveAt&&next%moveAt===0&&lastBreak.current!==next){lastBreak.current=next;if(isScreenEnabled("break")){setMessage("حان وقت الحركة — خذ استراحة واقعية");startExercise();notify("وقت الحركة","انهض بهدوء ومدد كتفيك لدقيقة")}sendTelegramAlert("break","⏰ تذكير NAVIXA: حان وقت الحركة — دقيقة واحدة تكفي")}const drinkAt=waterMinutes*60;if(next>=drinkAt&&next%drinkAt===0&&lastWater.current!==next){lastWater.current=next;if(isScreenEnabled("water"))notify("تذكير الماء","خذ كوب ماء وحافظ على نشاطك");sendTelegramAlert("water","💧 تذكير NAVIXA: وقت شرب كوب ماء")}if(next>0&&next%300===0){const minutes=Math.floor(next/60);setSessionAlert(`أكملت ${minutes} دقائق — خذ نفسًا وراجع وضعيتك`);notify("جلسة صحية",`أكملت ${minutes} دقائق من الجلسة`)}return next}),1000);return()=>clearInterval(timer)},[monitoring,breakMinutes,waterMinutes]);
  const analyse=()=>{if(!video.current||!pose.current||!stream.current)return;if(video.current.readyState>=2&&video.current.currentTime!==lastVideo.current){lastVideo.current=video.current.currentTime;const points=pose.current.detectForVideo(video.current,performance.now()).landmarks[0];if(!points){setPosture("missing");setMessage("الصورة غير واضحة — نظّف عدسة الكاميرا، حسّن الإضاءة واقترب قليلًا")}else{const le=points[7],re=points[8],ls=points[11],rs=points[12],width=Math.max(Math.abs(ls.x-rs.x),.05),height=((ls.y+rs.y)/2-(le.y+re.y)/2)/width,tilt=Math.abs(ls.y-rs.y)/width,isGood=height>.34&&tilt<.18;if(isGood){goodFrames.current++;careFrames.current=0;if(goodFrames.current>8){setPosture("good");setMessage("وضعيتك متوازنة — استمر")}}else{careFrames.current++;goodFrames.current=0;if(careFrames.current>12){setPosture("care");setMessage("ارفع رأسك وأرخِ كتفيك قليلًا")}}}}frame.current=requestAnimationFrame(analyse)};
  const start=async()=>{stop(false);const run=++lifecycle.current;try{setPosture("loading");setMessage("نجهّز التحليل المحلي…");const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:640},height:{ideal:480}},audio:false});if(run!==lifecycle.current){media.getTracks().forEach(t=>t.stop());return}stream.current=media;if(video.current){video.current.srcObject=media;await video.current.play()}const vision=await FilesetResolver.forVisionTasks("/mediapipe");let detector:PoseLandmarker;try{detector=await PoseLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:"/mediapipe/pose_landmarker_lite.task",delegate:"GPU"},runningMode:"VIDEO",numPoses:1})}catch{detector=await PoseLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:"/mediapipe/pose_landmarker_lite.task",delegate:"CPU"},runningMode:"VIDEO",numPoses:1})}if(run!==lifecycle.current){detector.close();media.getTracks().forEach(t=>t.stop());return}pose.current=detector;setMonitoring(true);setPosture("good");setPrivacyNotice(true);setSessionAlert("الجلسة بدأت — سنذكّرك بالحركة كل فترة");setMessage("المراقبة تعمل داخل جهازك فقط");if("Notification" in window&&Notification.permission==="default")void Notification.requestPermission();analyse()}catch{if(run===lifecycle.current){stop(false);setPosture("idle");setMessage("تعذر تشغيل الكاميرا — تحقق من الصلاحية")}}};
  const stop=(show=true)=>{lifecycle.current++;if(frame.current)cancelAnimationFrame(frame.current);frame.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current){video.current.pause();video.current.srcObject=null}pose.current?.close();pose.current=null;lastVideo.current=-1;goodFrames.current=0;careFrames.current=0;setMonitoring(false);setPosture("idle");setPrivacyNotice(false);setSessionAlert(show?"تم إيقاف الجلسة والكاميرا فورًا":"جلسة جديدة جاهزة للبدء");if(show)setMessage("توقفت الكاميرا والمراقبة فورًا")};
  useEffect(()=>()=>stop(false),[]);
  const addWater=()=>{if(cups>=8)return;const next=cups+1,stamp=new Date().toISOString();setCups(next);setLastWaterAt(stamp);localStorage.setItem(`navixa-water-${today()}`,String(next));localStorage.setItem(`navixa-water-${today()}-last`,stamp);setMessage(next>=8?"ما شاء الله — اكتمل هدف الماء اليوم 💧":"صحة وعافية — تم تسجيل كوب ماء")};
  const removeWater=()=>{if(cups<=0)return;const next=cups-1;setCups(next);localStorage.setItem(`navixa-water-${today()}`,String(next));setMessage("تم تعديل عدد الأكواب")};
  const waterPercent=Math.round(cups/8*100),lastWaterLabel=lastWaterAt?new Intl.DateTimeFormat("ar-SA",{hour:"numeric",minute:"2-digit"}).format(new Date(lastWaterAt)):"لم يُسجّل بعد";
  const waterMix=(t:number)=>{const a=[7,94,61],b=[141,120,207];const rgb=a.map((c,i)=>Math.round(c+(b[i]-c)*t));return `rgb(${rgb.join(",")})`};
  return <section className="health-monitor" id="health" aria-labelledby="health-title">
    <div className="health-heading"><div><small>صحة NAVIXA · مراقبة ذكية</small><h2 id="health-title">اجلس بوعي، وتحرك في وقتك</h2><p>مؤشر وضعيتك يعمل محليًا داخل متصفحك مع تنبيهات خفيفة تساعدك على الاستمرار.</p></div><button className="health-emergency" onClick={()=>stop()}><span>■</span> إيقاف فوري</button></div>
    <div className="health-layout"><article className="posture-panel"><div className="posture-top"><div><small>مراقبة وضعية الجلوس</small><h3>{monitoring?"جلسة نشطة":"الكاميرا متوقفة"}</h3></div><span className={`posture-dot ${posture}`}>{posture==="good"?"وضعية جيدة":posture==="care"?"تحتاج تعديل":posture==="loading"?"جارٍ التحضير":posture==="missing"?"الصورة غير واضحة":"خصوصية مفعّلة"}</span></div><div className="health-video"><video ref={video} muted playsInline/>{!monitoring&&<div className="video-placeholder"><span>📷</span><b>لن تعمل الكاميرا إلا بموافقتك</b><small>شغّلها لتجربة التحليل المحلي</small></div>}{monitoring&&<i className="health-scan"/>}</div>{privacyNotice&&<div className="privacy-confirm"><span>✓</span><div><b>خصوصيتك واضحة</b><p>تحليل وضعيتك يتم محليًا في المتصفح ولا تُرفع أو تُحفظ صور الكاميرا.</p></div><button onClick={()=>setPrivacyNotice(false)}>تم، فهمت</button></div>}<div className="posture-message"><span className={posture}/><p><b>{message}</b><small>ضع الكاميرا أمامك ليظهر الرأس والكتفان بوضوح.</small></p></div><div className="health-buttons">{!monitoring?<button onClick={start}>📷 تفعيل الكاميرا والمراقبة</button>:<button className="stop" onClick={()=>stop()}>إنهاء الجلسة</button>}<button className="ghost" onClick={()=>{setSeconds(0);localStorage.setItem(`navixa-sitting-${today()}`,"0")}}>تصفير مدة اليوم</button></div></article>
      <aside className="health-side"><article className="sitting-card"><div className="session-card-head"><small>جلسة اليوم</small><em className={monitoring?"live":""}>{monitoring?"مراقبة نشطة":"جاهزة للبدء"}</em></div><b>{format(seconds)}</b><span className="session-progress"><i style={{width:`${Math.min(100,seconds/(breakMinutes*60)*100)}%`}}/></span><p className="session-alert">{sessionAlert||`التنبيه التالي بعد ${breakMinutes} دقيقة`}</p><p>تنبيه الحركة كل <select aria-label="مدة تذكير الحركة" value={breakMinutes} onChange={e=>setBreakMinutes(Number(e.target.value))}><option value="20">20 دقيقة</option><option value="30">30 دقيقة</option><option value="45">45 دقيقة</option><option value="60">60 دقيقة</option></select></p></article><article className="water-health"><div className="water-title"><span className="water-glass-icon">💧</span><p><small>ترطيبك اليوم</small><b>{cups}/8 أكواب</b></p><strong>{waterPercent}%</strong></div><div className="water-progress"><i style={{width:`${waterPercent}%`}}/></div><div className="water-dots" aria-label={`تم تسجيل ${cups} من 8 أكواب`}>{Array.from({length:8},(_,i)=><i key={i} className={i<cups?"filled":""} style={i<cups?{background:waterMix(i/7)}:{}}/>)}</div><div className="water-actions"><button onClick={addWater} disabled={cups>=8}>{cups>=8?"اكتمل الهدف ✓":"سجّل كوب ماء +"}</button><button className="water-undo" onClick={removeWater} disabled={cups<=0} aria-label="تراجع عن آخر كوب">−</button></div><p className="water-last">آخر تسجيل: <b>{lastWaterLabel}</b></p><label>تذكير كل <select value={waterMinutes} onChange={e=>setWaterMinutes(Number(e.target.value))}><option value="30">30 دقيقة</option><option value="60">60 دقيقة</option><option value="90">90 دقيقة</option></select></label></article><article className="exercise-card"><span>↗</span><div><small>استراحة حركية</small><b>تمدد واقعي بدون معدات</b><p>4 حركات · دقيقة واحدة · ببطء وأمان.</p></div><button onClick={startExercise}>ابدأ</button></article><EyeRestClock/><BreathingExercise/><article className="privacy-health"><span>✓</span><div><b>خصوصية واضحة</b><p>النموذج والكاميرا يعملان محليًا. زر الإيقاف يقطع الكاميرا فورًا.</p></div></article></aside></div>
    {exercise&&<div className="exercise-modal" onClick={()=>setExercise(false)}><article onClick={e=>e.stopPropagation()}><button aria-label="إغلاق التمرين" onClick={()=>setExercise(false)}>×</button><small>جلسة حركية · تمرين {exerciseIndex+1} من {exercises.length}</small><h3>{exercises[exerciseIndex].title}</h3><p className="exercise-focus">{exercises[exerciseIndex].focus}</p><p className="motion-caption">موشن توضيحي · نفّذ الحركة ببطء وبدون ألم</p><div className={`stretch-figure ${exercises[exerciseIndex].motion}`} aria-label={`صورة متحركة توضح ${exercises[exerciseIndex].name}`}><span/><i/><b/><em/></div><div className="exercise-timer"><b>{exerciseSeconds}</b><span>ثانية متبقية · تحرك بدون ألم</span></div><div className="exercise-progress"><i style={{width:`${Math.max(0,Math.min(100,(1-exerciseSeconds/exercises[exerciseIndex].duration)*100))}%`}}/></div><ol>{exercises[exerciseIndex].steps.map(step=><li key={step}>{step}</li>)}</ol><button className="done" onClick={()=>{if(exerciseIndex<exercises.length-1){const next=exerciseIndex+1;setExerciseIndex(next);setExerciseSeconds(exercises[next].duration);setMessage("ممتاز — انتقلنا للحركة التالية")}else{setExercise(false);setExerciseIndex(0);setExerciseSeconds(exercises[0].duration);setMessage("أحسنت — أكملت سلسلة التمارين")}}}>{exerciseIndex<exercises.length-1?"تمت الحركة — التالية":"تمت كل التمارين"}</button></article></div>}
  </section>
}
