export type D1Statement={bind:(...values:unknown[])=>D1Statement;all:<T=Record<string,unknown>>()=>Promise<{results:T[]}>;run:()=>Promise<unknown>};
export type D1Database={prepare:(sql:string)=>D1Statement};
export type ReferralSettings={enabled:string;monthly_reward_days:string;quarterly_reward_days:string;max_rewards_per_month:string;attribution_days:string};
type Profile={id:string;contact:string;referral_code:string;status:string};
type Attribution={id:string;referrer_profile_id:string;referral_code:string;referred_contact:string;checkout_intent_id:string;status:string;expires_at:string};
export const referralDefaults:ReferralSettings={enabled:"false",monthly_reward_days:"7",quarterly_reward_days:"14",max_rewards_per_month:"4",attribution_days:"30"};
export const clean=(value:unknown,limit:number)=>typeof value==="string"?value.replace(/\s+/g," ").trim().slice(0,limit):"";
export const email=(value:unknown)=>clean(value,160).toLowerCase();
export const validEmail=(value:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
export const validCode=(value:string)=>/^NVX-[A-Z0-9]{8}$/.test(value);
export const nowIso=()=>new Date().toISOString();
export const afterDays=(days:number)=>new Date(Date.now()+days*86400000).toISOString();
export function createCode(){const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";const bytes=new Uint8Array(8);crypto.getRandomValues(bytes);return `NVX-${Array.from(bytes,byte=>alphabet[byte%alphabet.length]).join("")}`;}

export async function ensureReferralSchema(database:D1Database){
  await database.prepare("CREATE TABLE IF NOT EXISTS navixa_referral_settings (setting_key TEXT PRIMARY KEY,setting_value TEXT NOT NULL,updated_at TEXT NOT NULL)").run();
  await database.prepare("CREATE TABLE IF NOT EXISTS navixa_referral_profiles (id TEXT PRIMARY KEY,contact TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL DEFAULT '',referral_code TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)").run();
  await database.prepare("CREATE TABLE IF NOT EXISTS navixa_referral_attributions (id TEXT PRIMARY KEY,referrer_profile_id TEXT NOT NULL,referral_code TEXT NOT NULL,referred_contact TEXT NOT NULL,checkout_intent_id TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL,expires_at TEXT NOT NULL,rewarded_at TEXT NOT NULL DEFAULT '')").run();
  await database.prepare("CREATE TABLE IF NOT EXISTS navixa_referral_rewards (id TEXT PRIMARY KEY,referrer_profile_id TEXT NOT NULL,attribution_id TEXT NOT NULL UNIQUE,provider_payment_id TEXT NOT NULL UNIQUE,plan TEXT NOT NULL,reward_days INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending_credit',applied_to_subscription_at TEXT NOT NULL DEFAULT '',reversed_at TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)").run();
  const now=nowIso();for(const [key,value] of Object.entries(referralDefaults))await database.prepare("INSERT OR IGNORE INTO navixa_referral_settings (setting_key,setting_value,updated_at) VALUES (?,?,?)").bind(key,value,now).run();
}
export async function readReferralSettings(database:D1Database){await ensureReferralSchema(database);const rows=await database.prepare("SELECT setting_key,setting_value FROM navixa_referral_settings").all<{setting_key:string;setting_value:string}>();const next={...referralDefaults};for(const row of rows.results)if(row.setting_key in next)next[row.setting_key as keyof ReferralSettings]=row.setting_value;return next;}
export async function createReferralProfile(database:D1Database,contactValue:string,displayName=""){await ensureReferralSchema(database);const contact=email(contactValue);if(!validEmail(contact))throw new Error("بريد غير صالح");const existing=await database.prepare("SELECT id,contact,referral_code,status FROM navixa_referral_profiles WHERE contact=? LIMIT 1").bind(contact).all<Profile>();if(existing.results[0])return existing.results[0];const now=nowIso();for(let attempt=0;attempt<4;attempt++){const profile:Profile={id:crypto.randomUUID(),contact,referral_code:createCode(),status:"active"};try{await database.prepare("INSERT INTO navixa_referral_profiles (id,contact,display_name,referral_code,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?)").bind(profile.id,contact,clean(displayName,80),profile.referral_code,"active",now,now).run();return profile}catch{if(attempt===3)throw new Error("تعذر إنشاء رمز الإحالة")}}throw new Error("تعذر إنشاء رمز الإحالة")}
export async function createAttribution(database:D1Database,referralCodeValue:string,referredContactValue:string,intentId:string){const settings=await readReferralSettings(database);if(settings.enabled!=="true")return null;const referralCode=clean(referralCodeValue,20).toUpperCase(),referredContact=email(referredContactValue);if(!validCode(referralCode)||!validEmail(referredContact))return null;const profiles=await database.prepare("SELECT id,contact,referral_code,status FROM navixa_referral_profiles WHERE referral_code=? LIMIT 1").bind(referralCode).all<Profile>();const profile=profiles.results[0];if(!profile||profile.status!=="active"||profile.contact===referredContact)return null;const active=await database.prepare("SELECT id FROM navixa_subscribers WHERE contact=? AND status='active' LIMIT 1").bind(referredContact).all<{id:string}>();if(active.results.length)return null;const existing=await database.prepare("SELECT id FROM navixa_referral_attributions WHERE checkout_intent_id=? LIMIT 1").bind(intentId).all<{id:string}>();if(existing.results.length)return null;const now=nowIso(),days=Math.max(1,Math.min(90,Number(settings.attribution_days)||30));const attribution:Attribution={id:crypto.randomUUID(),referrer_profile_id:profile.id,referral_code:referralCode,referred_contact:referredContact,checkout_intent_id:intentId,status:"pending",expires_at:afterDays(days)};await database.prepare("INSERT INTO navixa_referral_attributions (id,referrer_profile_id,referral_code,referred_contact,checkout_intent_id,status,created_at,expires_at,rewarded_at) VALUES (?,?,?,?,?,'pending',?,?, '')").bind(attribution.id,profile.id,referralCode,referredContact,intentId,now,attribution.expires_at).run();return attribution;}
export async function applyPendingCredits(database:D1Database,contactValue:string){const contact=email(contactValue);const profileRows=await database.prepare("SELECT id,contact,referral_code,status FROM navixa_referral_profiles WHERE contact=? LIMIT 1").bind(contact).all<Profile>();const profile=profileRows.results[0];if(!profile)return 0;const rewards=await database.prepare("SELECT id,reward_days FROM navixa_referral_rewards WHERE referrer_profile_id=? AND status='pending_credit'").bind(profile.id).all<{id:string;reward_days:number}>();const days=rewards.results.reduce((total,row)=>total+Math.max(0,Number(row.reward_days)||0),0);if(!days)return 0;const subscriberRows=await database.prepare("SELECT id,subscription_ends_at FROM navixa_subscribers WHERE contact=? AND status='active' LIMIT 1").bind(contact).all<{id:string;subscription_ends_at:string}>();const subscriber=subscriberRows.results[0];if(!subscriber)return 0;const base=Math.max(Date.now(),new Date(subscriber.subscription_ends_at||0).getTime()||0),end=new Date(base+days*86400000).toISOString(),now=nowIso();await database.prepare("UPDATE navixa_subscribers SET subscription_ends_at=?,updated_at=? WHERE id=?").bind(end,now,subscriber.id).run();for(const reward of rewards.results)await database.prepare("UPDATE navixa_referral_rewards SET status='applied',applied_to_subscription_at=?,updated_at=? WHERE id=?").bind(now,now,reward.id).run();return days;}
export async function rewardReferralAfterVerifiedPayment(database:D1Database,checkoutIntentId:string,paymentId:string,plan:"monthly"|"quarterly"){const settings=await readReferralSettings(database);if(settings.enabled!=="true")return {rewarded:false,reason:"disabled"};const rows=await database.prepare("SELECT id,referrer_profile_id,referral_code,referred_contact,checkout_intent_id,status,expires_at FROM navixa_referral_attributions WHERE checkout_intent_id=? LIMIT 1").bind(checkoutIntentId).all<Attribution>();const attribution=rows.results[0];if(!attribution||attribution.status!=="pending"||new Date(attribution.expires_at).getTime()<Date.now())return {rewarded:false,reason:"not_eligible"};const duplicate=await database.prepare("SELECT id FROM navixa_referral_rewards WHERE attribution_id=? OR provider_payment_id=? LIMIT 1").bind(attribution.id,paymentId).all<{id:string}>();if(duplicate.results.length)return {rewarded:false,reason:"duplicate"};const monthAgo=new Date(Date.now()-31*86400000).toISOString(),countRows=await database.prepare("SELECT COUNT(*) AS count FROM navixa_referral_rewards WHERE referrer_profile_id=? AND created_at>=? AND status<>'reversed'").bind(attribution.referrer_profile_id,monthAgo).all<{count:number}>();const ceiling=Math.max(1,Math.min(20,Number(settings.max_rewards_per_month)||4));if(Number(countRows.results[0]?.count||0)>=ceiling)return {rewarded:false,reason:"monthly_limit"};const days=plan==="quarterly"?Math.max(1,Number(settings.quarterly_reward_days)||14):Math.max(1,Number(settings.monthly_reward_days)||7),now=nowIso();const subscribers=await database.prepare("SELECT id,status,subscription_ends_at,trial_ends_at FROM navixa_subscribers WHERE contact=(SELECT contact FROM navixa_referral_profiles WHERE id=?) LIMIT 1").bind(attribution.referrer_profile_id).all<{id:string;status:string;subscription_ends_at:string;trial_ends_at:string}>();const subscriber=subscribers.results[0];let status="pending_credit",applied="";if(subscriber&&(subscriber.status==="active"||subscriber.status==="trial")){const column=subscriber.status==="active"?"subscription_ends_at":"trial_ends_at",current=subscriber.status==="active"?subscriber.subscription_ends_at:subscriber.trial_ends_at,base=Math.max(Date.now(),new Date(current||0).getTime()||0),end=new Date(base+days*86400000).toISOString();await database.prepare(`UPDATE navixa_subscribers SET ${column}=?,updated_at=? WHERE id=?`).bind(end,now,subscriber.id).run();status="applied";applied=now;}
  await database.prepare("INSERT INTO navixa_referral_rewards (id,referrer_profile_id,attribution_id,provider_payment_id,plan,reward_days,status,applied_to_subscription_at,reversed_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?, '',?,?)").bind(crypto.randomUUID(),attribution.referrer_profile_id,attribution.id,paymentId,plan,days,status,applied,now,now).run();await database.prepare("UPDATE navixa_referral_attributions SET status='rewarded',rewarded_at=? WHERE id=?").bind(now,attribution.id).run();return {rewarded:true,days,status};}
