"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import FeatureAccessGate from "../FeatureAccessGate";
import { readAcademicReminders, type AcademicReminder } from "../academicReminders";
import "./progress.css";

type Task={title:string;done:boolean;meta?:string};
const day=(offset=0)=>{const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)};
const dateText=(value:string)=>new Intl.DateTimeFormat("ar-SA",{weekday:"long",day:"numeric",month:"long"}).format(new Date(`${value}T12:00:00+03:00`));

export default function ProgressPage(){const [tasks,setTasks]=useState<Task[]>([]),[reminders,setReminders]=useState<AcademicReminder[]>([]),[ready,setReady]=useState(false);useEffect(()=>{try{setTasks(JSON.parse(localStorage.getItem("navixa-life-tasks")||"[]"))}catch{}setReminders(readAcademicReminders());setReady(true)},[]);const days=useMemo(()=>Array.from({length:7},(_,index)=>day(index-6)),[]);const sessions=ready?days.map(date=>Number(localStorage.getItem(`navixa-sessions-${date}`)||0)):days.map(()=>0);const totalSessions=sessions.reduce((sum,value)=>sum+value,0),completed=tasks.filter(task=>task.done).length,pending=tasks.length-completed;let streak=0;if(ready)for(let index=0;index<30;index+=1){if(Number(localStorage.getItem(`navixa-sessions-${day(-index)}`)||0)>0)streak+=1;else break}const upcoming=reminders.filter(item=>item.date>=day()).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,3);return <main className="progress-page" dir="rtl"><FeatureAccessGate feature="صفحة تقدّمي"><header className="progress-topbar"><Link href="/" className="progress-brand"><img src="/navixa-mark.webp" alt=""/><b dir="ltr">NAVIXA <em>SA</em></b></Link><nav><Link href="/today">يومي</Link><Link href="/reminders">التذكيرات</Link><Link href="/account">حسابي</Link></nav></header><section className="progress-hero"><div><small>تقدّمي هذا الأسبوع</small><h1>خطوات صغيرة، أثر واضح.</h1><p>هذا الملخص يقرأ ما حفظته على جهازك ومواعيدك القريبة فقط، ولا يراقبك أو يشارك بياناتك.</p></div><Link href="/today">رتّب يومي ←</Link></section>{ready&&<><section className="progress-metrics"><article><small>جلسات تركيز</small><b>{totalSessions}</b><em>خلال 7 أيام</em></article><article><small>استمرارية</small><b>{streak}</b><em>يومًا متتابعًا</em></article><article><small>مهام مكتملة</small><b>{completed}</b><em>{pending?`${pending} متبقية`:"يومك مرتب"}</em></article><article><small>أقرب تذكير</small><b>{upcoming.length?upcoming[0].title:"—"}</b><em>{upcoming.length?dateText(upcoming[0].date):"أضف موعدًا من يومي"}</em></article></section><section className="progress-content"><article className="progress-chart"><div><small>إيقاع التركيز</small><h2>جلساتك اليومية</h2></div><div className="progress-bars">{sessions.map((count,index)=><div key={days[index]}><i style={{height:`${Math.max(8,Math.min(100,count*22))}%`}}/><b>{count}</b><small>{index===6?"اليوم":new Intl.DateTimeFormat("ar-SA",{weekday:"short"}).format(new Date(`${days[index]}T12:00:00`))}</small></div>)}</div></article><article className="progress-upcoming"><div><small>القادم</small><h2>مواعيدك القريبة</h2></div>{upcoming.length?upcoming.map(item=><div key={item.id}><span>◷</span><b>{item.title}</b><small>{dateText(item.date)} · تذكير قبل يوم</small></div>):<p>لا يوجد موعد قريب. أضف اختبارًا أو اجتماعًا من «يومي».</p>}<Link href="/reminders">إدارة التذكيرات ←</Link></article></section></>}</FeatureAccessGate></main>}
