import { NextResponse } from "next/server.js";
import { ensureImportantReminderSchema } from "../../../worker/importantReminders.ts";
import { resolveUserSession, trustedUserMutation, type D1Database } from "../../../worker/userAuth.ts";
type Stmt={bind:(...v:unknown[])=>Stmt;all:<T=Record<string,unknown>>()=>Promise<{results:T[]}>;run:()=>Promise<unknown>}; type Db=D1Database&{prepare:(sql:string)=>Stmt};
async function db():Promise<Db|null>{try{return (await import("cloudflare:workers") as {env?:{DB?:Db}}).env?.DB||null}catch{return (globalThis as {DB?:Db}).DB||null}}
const reply=(body:Record<string,unknown>,status=200)=>NextResponse.json(body,{status,headers:{"Cache-Control":"private, no-store",Vary:"Cookie"}});
export async function GET(request:Request){const database=await db();if(!database)return reply({error:"التخزين غير مهيأ"},503);const session=await resolveUserSession(request,database);if(!session)return reply({error:"سجّل الدخول أولًا"},401);await ensureImportantReminderSchema(database);const reminders=await database.prepare("SELECT id,title,due_at,email_enabled,telegram_enabled,email_status,telegram_status FROM navixa_important_reminders WHERE user_id=? AND due_at>=? ORDER BY due_at LIMIT 24").bind(session.userId,new Date().toISOString()).all();return reply({reminders:reminders.results})}
export async function POST(request:Request){if(!trustedUserMutation(request))return reply({error:"مصدر الطلب غير موثوق"},403);const database=await db();if(!database)return reply({error:"التخزين غير مهيأ"},503);const session=await resolveUserSession(request,database);if(!session)return reply({error:"سجّل الدخول أولًا"},401);const body=await request.json().catch(()=>({})) as {title?:unknown;dueAt?:unknown;email?:unknown;telegram?:unknown};const title=typeof body.title==="string"?body.title.trim().slice(0,120):"",dueAt=typeof body.dueAt==="string"?body.dueAt:"",due=Date.parse(dueAt),email=body.email===true,telegram=body.telegram===true;if(!title||!Number.isFinite(due)||due<=Date.now()||(!email&&!telegram))return reply({error:"بيانات التذكير المهمة غير صالحة"},400);await ensureImportantReminderSchema(database);const now=new Date().toISOString();await database.prepare("INSERT INTO navixa_important_reminders(id,user_id,title,due_at,email_enabled,telegram_enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(user_id,title,due_at) DO UPDATE SET email_enabled=excluded.email_enabled,telegram_enabled=excluded.telegram_enabled,updated_at=excluded.updated_at").bind(crypto.randomUUID(),session.userId,title,new Date(due).toISOString(),email?1:0,telegram?1:0,now,now).run();return reply({ok:true})}
export async function DELETE(request:Request){if(!trustedUserMutation(request))return reply({error:"مصدر الطلب غير موثوق"},403);const database=await db();if(!database)return reply({error:"التخزين غير مهيأ"},503);const session=await resolveUserSession(request,database);if(!session)return reply({error:"سجّل الدخول أولًا"},401);const id=new URL(request.url).searchParams.get("id")||"";if(!/^[0-9a-f-]{20,}$/i.test(id))return reply({error:"معرّف غير صالح"},400);await ensureImportantReminderSchema(database);await database.prepare("DELETE FROM navixa_important_reminders WHERE id=? AND user_id=?").bind(id,session.userId).run();return reply({ok:true})}
