import { NextResponse } from "next/server.js";
import { ADMIN_SESSION_COOKIE, isTrustedSameOriginRequest, readCookie, resolveAdminJwtSecret, verifyAdminSessionToken } from "../../../../worker/adminAuth.ts";

type D1Statement={bind:(...values:unknown[])=>D1Statement;run:()=>Promise<unknown>;all:<T=Record<string,unknown>>()=>Promise<{results:T[]}>};
type D1Database={prepare:(sql:string)=>D1Statement};
const text=(value:unknown,limit=120)=>typeof value==="string"?value.trim().slice(0,limit):"";
const logo=(value:unknown)=>{const valueText=text(value,500);return /^https:\/\//i.test(valueText)?valueText:""};
const validDateTime=(value:string)=>/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2})?(?:[+-]\d{2}:\d{2}|Z)?$/.test(value);
const validStatus=(value:unknown)=>value==="live"||value==="finished"?value:"scheduled";
async function db():Promise<D1Database|null>{try{return (await import("cloudflare:workers") as {env?:{DB?:D1Database}}).env?.DB||null}catch{return (globalThis as {DB?:D1Database}).DB||null}}
async function schema(database:D1Database){await database.prepare("CREATE TABLE IF NOT EXISTS navixa_admin_manual_matches (match_id TEXT PRIMARY KEY, competition_id TEXT NOT NULL, league_name TEXT NOT NULL, home_name TEXT NOT NULL, away_name TEXT NOT NULL, home_logo TEXT NOT NULL DEFAULT '', away_logo TEXT NOT NULL DEFAULT '', kickoff TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'scheduled', home_score INTEGER, away_score INTEGER, venue TEXT NOT NULL DEFAULT '', venue_city TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL)").run()}
async function allowed(request:Request,mutation=false){if(mutation&&!isTrustedSameOriginRequest(request))return false;const secret=await resolveAdminJwtSecret();return Boolean(secret&&await verifyAdminSessionToken(readCookie(request,ADMIN_SESSION_COOKIE),secret))}
const id=()=>`admin-manual-${crypto.randomUUID()}`;

export async function GET(request:Request){if(!await allowed(request))return NextResponse.json({error:"غير مصرح"},{status:401,headers:{"Cache-Control":"no-store"}});const database=await db();if(!database)return NextResponse.json({matches:[],configured:false},{headers:{"Cache-Control":"no-store"}});await schema(database);const rows=await database.prepare("SELECT * FROM navixa_admin_manual_matches ORDER BY kickoff ASC LIMIT 200").all<Record<string,unknown>>();return NextResponse.json({configured:true,matches:rows.results.map(row=>({id:String(row.match_id||""),competitionId:String(row.competition_id||""),league:String(row.league_name||""),home:String(row.home_name||""),away:String(row.away_name||""),homeLogo:String(row.home_logo||""),awayLogo:String(row.away_logo||""),kickoff:String(row.kickoff||""),status:String(row.status||"scheduled"),venue:String(row.venue||""),venueCity:String(row.venue_city||"")}))},{headers:{"Cache-Control":"no-store"}})}

export async function POST(request:Request){if(!await allowed(request,true))return NextResponse.json({error:"غير مصرح"},{status:401,headers:{"Cache-Control":"no-store"}});const body=await request.json().catch(()=>({}));const matchId=text(body.matchId,160)||id(),competitionId=text(body.competitionId,80),league=text(body.league,120),home=text(body.home,120),away=text(body.away,120),kickoff=text(body.kickoff,40);if(!competitionId||!league||!home||!away||!validDateTime(kickoff))return NextResponse.json({error:"بيانات المباراة غير مكتملة"},{status:400,headers:{"Cache-Control":"no-store"}});const database=await db();if(!database)return NextResponse.json({error:"قاعدة البيانات غير مهيأة"},{status:503});await schema(database);const now=new Date().toISOString();await database.prepare("INSERT INTO navixa_admin_manual_matches (match_id,competition_id,league_name,home_name,away_name,home_logo,away_logo,kickoff,status,venue,venue_city,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(match_id) DO UPDATE SET competition_id=excluded.competition_id,league_name=excluded.league_name,home_name=excluded.home_name,away_name=excluded.away_name,home_logo=excluded.home_logo,away_logo=excluded.away_logo,kickoff=excluded.kickoff,status=excluded.status,venue=excluded.venue,venue_city=excluded.venue_city,updated_at=excluded.updated_at").bind(matchId,competitionId,league,home,away,logo(body.homeLogo),logo(body.awayLogo),kickoff,validStatus(body.status),text(body.venue),text(body.venueCity),now,now).run();return NextResponse.json({ok:true,matchId},{headers:{"Cache-Control":"no-store"}})}

export async function DELETE(request:Request){if(!await allowed(request,true))return NextResponse.json({error:"غير مصرح"},{status:401,headers:{"Cache-Control":"no-store"}});const matchId=text(new URL(request.url).searchParams.get("matchId"),160);if(!matchId)return NextResponse.json({error:"معرّف المباراة مطلوب"},{status:400});const database=await db();if(!database)return NextResponse.json({error:"قاعدة البيانات غير مهيأة"},{status:503});await schema(database);await database.prepare("DELETE FROM navixa_admin_manual_matches WHERE match_id=?").bind(matchId).run();return NextResponse.json({ok:true},{headers:{"Cache-Control":"no-store"}})}
