import { NextResponse } from "next/server.js";
import { ADMIN_SESSION_COOKIE,isTrustedSameOriginRequest,readCookie,resolveAdminJwtSecret,verifyAdminSessionToken } from "../../../../worker/adminAuth.ts";

type D1Statement={bind:(...values:unknown[])=>D1Statement;run:()=>Promise<unknown>;all:<T=Record<string,unknown>>()=>Promise<{results:T[]}>};
type D1Database={prepare:(sql:string)=>D1Statement};
async function db():Promise<D1Database|null>{try{return (await import("cloudflare:workers") as {env?:{DB?:D1Database}}).env?.DB||null}catch{return (globalThis as {DB?:D1Database}).DB||null}}
async function authorized(request:Request,mutation=false){if(mutation&&!isTrustedSameOriginRequest(request))return false;const secret=await resolveAdminJwtSecret();return Boolean(secret&&await verifyAdminSessionToken(readCookie(request,ADMIN_SESSION_COOKIE),secret))}
async function schema(database:D1Database){await database.prepare("CREATE TABLE IF NOT EXISTS navixa_team_aliases (source_name TEXT PRIMARY KEY, arabic_name TEXT NOT NULL, updated_at TEXT NOT NULL)").run()}
export async function GET(request:Request){if(!await authorized(request))return NextResponse.json({error:"غير مصرح"},{status:401,headers:{"Cache-Control":"no-store"}});const database=await db();if(!database)return NextResponse.json({aliases:[]},{headers:{"Cache-Control":"no-store"}});await schema(database);const result=await database.prepare("SELECT source_name,arabic_name,updated_at FROM navixa_team_aliases ORDER BY source_name LIMIT 500").all<{source_name:string;arabic_name:string;updated_at:string}>();return NextResponse.json({aliases:result.results.map(row=>({sourceName:row.source_name,arabicName:row.arabic_name,updatedAt:row.updated_at}))},{headers:{"Cache-Control":"no-store"}})}
export async function POST(request:Request){if(!await authorized(request,true))return NextResponse.json({error:"غير مصرح"},{status:401,headers:{"Cache-Control":"no-store"}});const body=await request.json().catch(()=>({})) as {sourceName?:unknown;arabicName?:unknown};const sourceName=typeof body.sourceName==="string"?body.sourceName.trim().toLowerCase().slice(0,100):"";const arabicName=typeof body.arabicName==="string"?body.arabicName.trim().slice(0,100):"";if(!sourceName||!arabicName)return NextResponse.json({error:"أدخل الاسم القادم من المصدر والاسم العربي"},{status:400,headers:{"Cache-Control":"no-store"}});const database=await db();if(!database)return NextResponse.json({error:"قاعدة البيانات غير مهيأة"},{status:503});await schema(database);await database.prepare("INSERT INTO navixa_team_aliases (source_name,arabic_name,updated_at) VALUES (?,?,?) ON CONFLICT(source_name) DO UPDATE SET arabic_name=excluded.arabic_name,updated_at=excluded.updated_at").bind(sourceName,arabicName,new Date().toISOString()).run();return NextResponse.json({ok:true},{headers:{"Cache-Control":"no-store"}})}
export async function DELETE(request:Request){if(!await authorized(request,true))return NextResponse.json({error:"غير مصرح"},{status:401,headers:{"Cache-Control":"no-store"}});const sourceName=new URL(request.url).searchParams.get("sourceName")?.trim().toLowerCase()||"";if(!sourceName)return NextResponse.json({error:"اسم المصدر مطلوب"},{status:400});const database=await db();if(!database)return NextResponse.json({ok:true});await schema(database);await database.prepare("DELETE FROM navixa_team_aliases WHERE source_name=?").bind(sourceName).run();return NextResponse.json({ok:true},{headers:{"Cache-Control":"no-store"}})}
