import type { Metadata } from "next";
import Link from "next/link";
import "../feature-guides.css";

export const metadata: Metadata = { title:"دليل تنظيم اليوم والتذكيرات والخصوصية",description:"أدلة عربية عملية من NAVIXA لتنظيم اليوم، اختيار التذكيرات، والمحافظة على خصوصيتك أثناء استخدام أدوات الإنتاجية.",alternates:{canonical:"/guides"}};

const guides=[
  {id:"day",eyebrow:"تنظيم اليوم",title:"كيف ترتّب يومك من دون أن تمتلئ قائمتك؟",intro:"ابدأ بما تحتاجه اليوم، لا بما تريد إنجازه في شهر كامل. التنظيم الجيد لا يعني قائمة أطول؛ بل يعني أن تعرف ما هي الخطوة التالية الواضحة.",steps:["اكتب أولوية واحدة لا تحتاج شرحًا طويلًا، مثل: مراجعة فصل محدد أو إرسال رسالة محددة.","أضف ما له وقت ثابت كموعد منفصل، حتى لا يختلط مع المهام التي يمكن تأجيلها.","اختر مدة تركيز قصيرة، ثم راجع ما اكتمل بدل التنقل بين عشر مهام."],cta:"افتح صفحة يومي",href:"/today"},
  {id:"reminders",eyebrow:"التذكيرات",title:"كيف تختار تذكيرًا مفيدًا بدل تنبيه يزعجك؟",intro:"التذكير يجب أن يصل عندما يساعدك على اتخاذ إجراء. التذكيرات اليومية البسيطة تبقى داخل الموقع، أما ما لا يمكن تفويته فيستحق قناة خارجية تختارها أنت.",steps:["صنّف التذكير: يومي، موعد قريب، أو أمر مهم لا تريد تفويته.","فعّل البريد أو Telegram فقط للتذكيرات المهمة ذات وقت محدد.","احذف التذكير بعد انتهاء الحاجة منه؛ هذا يحافظ على مركزك واضحًا وهادئًا."],cta:"افتح مركز التذكيرات",href:"/reminders"},
  {id:"privacy",eyebrow:"خصوصية عملية",title:"كيف تحافظ على خصوصيتك أثناء تنظيم يومك؟",intro:"لا تحتاج كل أداة إنتاجية إلى نسخة من حياتك. تفضيلاتك اليومية وملخص تقدّمك يمكن أن تبقى على جهازك، بينما تستخدم القنوات الخارجية فقط عندما تختار إرسال تذكير مهم.",steps:["راجع القناة قبل الحفظ: داخل الموقع للتذكيرات الخفيفة، وخارج الموقع عند الحاجة الحقيقية.","لا تضع كلمات مرور أو رموز تحقق أو تفاصيل حساسة داخل عناوين التذكيرات.","استخدم صفحة تقدّمي للمراجعة الأسبوعية بدل مشاركة قائمة مهامك مع أي جهة."],cta:"اقرأ عن خصوصية NAVIXA",href:"/local-privacy"},
];

export default function GuidesPage(){return <main className="feature-guide" dir="rtl"><div className="feature-guide-inner"><Link href="/" className="feature-guide-nav">← العودة إلى NAVIXA SA</Link><header className="feature-guide-hero"><span className="feature-guide-kicker">أدلة NAVIXA العملية</span><h1>تنظيم أهدأ، وتذكيرات أوضح، وخصوصية أقرب لك.</h1><p>صفحات عربية قصيرة تساعدك على استخدام أدوات التنظيم بوضوح. لا تحتاج إلى نسخ حياتك في قائمة واحدة كي يبدأ يومك بشكل أفضل.</p><Link href="/today" className="feature-guide-cta">ابدأ من يومي</Link></header>{guides.map(guide=><article key={guide.id} className="feature-guide-note" id={guide.id}><span className="feature-guide-kicker">{guide.eyebrow}</span><h2>{guide.title}</h2><p>{guide.intro}</p><div className="feature-guide-grid">{guide.steps.map((step,index)=><section className="feature-guide-card" key={step}><h3>الخطوة {index+1}</h3><p>{step}</p></section>)}</div><Link href={guide.href} className="feature-guide-cta">{guide.cta} ←</Link></article>)}<footer className="feature-guide-footer">هذه الأدلة معلومات عملية عامة وليست بديلًا عن استشارة مهنية متخصصة عند الحاجة.</footer></div></main>}
