"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useAdminAuth } from "../useAdminAuth";
import "./support.css";

type Ticket = { id: string; product: string; category: string; subject: string; description: string; status: string; admin_reply: string; created_at: string; updated_at: string };
const statuses = [{ id: "new", label: "جديدة" }, { id: "in_review", label: "قيد المراجعة" }, { id: "waiting_user", label: "بانتظار المستخدم" }, { id: "resolved", label: "محلولة" }, { id: "closed", label: "مغلقة" }];
export default function AdminSupportPage() { const { allowed, checking } = useAdminAuth(); const [tickets, setTickets] = useState<Ticket[]>([]), [notice, setNotice] = useState(""), [saving, setSaving] = useState(""); const load = async () => { const response = await fetch("/api/admin/support/tickets", { cache: "no-store" }); const data = await response.json(); if (response.ok) setTickets(Array.isArray(data.tickets) ? data.tickets : []); else setNotice(data.error || "تعذر تحميل التذاكر"); }; useEffect(() => { if (allowed) void load(); }, [allowed]); const save = async (ticket: Ticket, status: string, reply: string) => { setSaving(ticket.id); setNotice(""); try { const response = await fetch("/api/admin/support/tickets", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: ticket.id, status, reply }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "تعذر حفظ التذكرة"); setNotice("تم حفظ تحديث الدعم."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "تعذر حفظ التذكرة"); } finally { setSaving(""); } }; if (checking || !allowed) return null; return <main className="admin-support" dir="rtl"><header><Link href="/admin">← الإدارة</Link><div><small>NAVIXA SA</small><h1>صندوق الدعم الموحد</h1><p>تذاكر NAVIXA وLearning وFitness وKids. لا تعرض هذه الشاشة البريد أو بيانات الجلسات.</p></div></header>{notice && <p className="admin-support-notice" role="status">{notice}</p>}<section>{tickets.length === 0 ? <p className="admin-support-empty">لا توجد تذاكر دعم.</p> : tickets.map(ticket => <TicketEditor key={ticket.id} ticket={ticket} saving={saving === ticket.id} onSave={save} />)}</section></main>; }
function TicketEditor({ ticket, saving, onSave }: { ticket: Ticket; saving: boolean; onSave: (ticket: Ticket, status: string, reply: string) => void }) { const [status, setStatus] = useState(ticket.status), [reply, setReply] = useState(ticket.admin_reply); return <article className="admin-ticket"><div className="admin-ticket-meta"><span>{ticket.product}</span><span>{ticket.category}</span><time>{new Date(ticket.updated_at).toLocaleString("ar-SA")}</time></div><h2>{ticket.subject}</h2><p className="admin-ticket-description">{ticket.description}</p><label>الحالة<select value={status} onChange={event => setStatus(event.target.value)}>{statuses.map(item => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>رد داخل مركز الدعم<textarea value={reply} onChange={event => setReply(event.target.value)} maxLength={1600} placeholder="رد واضح لا يتضمن طلب أي كلمة مرور أو رمز تحقق أو بيانات دفع." /></label><button onClick={() => onSave(ticket, status, reply)} disabled={saving}>{saving ? "جارٍ الحفظ…" : "حفظ التحديث"}</button></article>; }
