import { NextResponse } from "next/server.js";
import { ADMIN_SESSION_COOKIE,isTrustedSameOriginRequest,readCookie,resolveAdminJwtSecret,verifyAdminSessionToken } from "../../../../worker/adminAuth.ts";

type D1Statement={bind:(...values:unknown[])=>D1Statement;all:<T=Record<string,unknown>>()=>Promise<{results:T[]}>;run:()=>Promise<unknown>};
type D1Database={prepare:(sql:string)=>D1Statement};
const clean=(value:unknown,limit:number)=>typeof value==="string"?value.replace(/\s+/g," ").trim().slice(0,limit):"";
async function db():Promise<D1Database|null>{try{return (await import("cloudflare:workers") as {env?:{DB?:D1Database}}).env?.DB||null}catch{return (globalThis as {DB?:D1Database}).DB||null}}
async function schema(database:D1Database){await database.prepare("CREATE TABLE IF NOT EXISTS navixa_assistant_learning_contributions (id TEXT PRIMARY KEY,question_text TEXT NOT NULL,response_text TEXT NOT NULL,sensitivity TEXT NOT NULL DEFAULT 'standard',explicit_sensitive_consent INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL,reviewed_at TEXT NOT NULL DEFAULT '')").run();await database.prepare("CREATE TABLE IF NOT EXISTS navixa_assistant_global_patterns (id TEXT PRIMARY KEY,trigger_text TEXT NOT NULL,response_text TEXT NOT NULL,source_contribution_id TEXT NOT NULL DEFAULT '',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)").run()}
async function allowed(request:Request){const secret=await resolveAdminJwtSecret();return Boolean(secret&&isTrustedSameOriginRequest(request)&&await verifyAdminSessionToken(readCookie(request,ADMIN_SESSION_COOKIE),secret))}

export async function GET(request:Request){if(!await allowed(request))return NextResponse.json({error:"غير مصرح"},{status:401,headers:{"Cache-Control":"no-store"}});const database=await db();if(!database)return NextResponse.json({contributions:[],patterns:[]},{headers:{"Cache-Control":"no-store"}});await schema(database);const [pending,patterns]=await Promise.all([database.prepare("SELECT id,question_text,response_text,sensitivity,created_at FROM navixa_assistant_learning_contributions WHERE status='pending' ORDER BY created_at DESC LIMIT 30").all(),database.prepare("SELECT id,trigger_text,response_text,active,updated_at FROM navixa_assistant_global_patterns ORDER BY updated_at DESC LIMIT 40").all()]);return NextResponse.json({contributions:pending.results,patterns:patterns.results},{headers:{"Cache-Control":"no-store"}})}

export async function POST(request:Request){if(!await allowed(request))return NextResponse.json({error:"غير مصرح"},{status:401,headers:{"Cache-Control":"no-store"}});const body=await request.json().catch(()=>({})) as {action?:unknown;id?:unknown;trigger?:unknown;response?:unknown;active?:unknown};const action=clean(body.action,20),id=clean(body.id,80);if(!id)return NextResponse.json({error:"المعرف مطلوب"},{status:400,headers:{"Cache-Control":"no-store"}});const database=await db();if(!database)return NextResponse.json({error:"التخزين غير مهيأ"},{status:503,headers:{"Cache-Control":"no-store"}});await schema(database);const now=new Date().toISOString();if(action==="approve"){const trigger=clean(body.trigger,160),response=clean(body.response,500);if(trigger.length<2||response.length<2)return NextResponse.json({error:"اكتب عبارة فهم وردًا مناسبًا"},{status:400,headers:{"Cache-Control":"no-store"}});await database.prepare("UPDATE navixa_assistant_learning_contributions SET status='approved',reviewed_at=? WHERE id=?").bind(now,id).run();await database.prepare("INSERT INTO navixa_assistant_global_patterns (id,trigger_text,response_text,source_contribution_id,active,created_at,updated_at) VALUES (?,?,?,?,1,?,?)").bind(crypto.randomUUID(),trigger,response,id,now,now).run();return NextResponse.json({ok:true},{headers:{"Cache-Control":"no-store"}})}if(action==="reject"){await database.prepare("UPDATE navixa_assistant_learning_contributions SET status='rejected',reviewed_at=? WHERE id=?").bind(now,id).run();return NextResponse.json({ok:true},{headers:{"Cache-Control":"no-store"}})}if(action==="toggle"){await database.prepare("UPDATE navixa_assistant_global_patterns SET active=?,updated_at=? WHERE id=?").bind(body.active===true?1:0,now,id).run();return NextResponse.json({ok:true},{headers:{"Cache-Control":"no-store"}})}return NextResponse.json({error:"إجراء غير صالح"},{status:400,headers:{"Cache-Control":"no-store"}})}

export async function DELETE(request:Request){if(!await allowed(request))return NextResponse.json({error:"غير مصرح"},{status:401,headers:{"Cache-Control":"no-store"}});const url=new URL(request.url),id=clean(url.searchParams.get("id"),80);if(!id)return NextResponse.json({error:"المعرف مطلوب"},{status:400,headers:{"Cache-Control":"no-store"}});const database=await db();if(!database)return NextResponse.json({ok:true},{headers:{"Cache-Control":"no-store"}});await schema(database);await database.prepare("DELETE FROM navixa_assistant_global_patterns WHERE id=?").bind(id).run();return NextResponse.json({ok:true},{headers:{"Cache-Control":"no-store"}})}
