"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import "./support.css";

type Ticket = { id: string; product: string; category: string; subject: string; status: string; admin_reply: string; created_at: string; updated_at: string };
const products = [{ id: "main", label: "NAVIXA الرئيسي" }, { id: "learning", label: "NAVIXA Learning" }, { id: "fitness", label: "NAVIXA Fitness" }, { id: "kids", label: "NAVIXA Kids" }];
const categories = [{ id: "account", label: "الحساب والدخول" }, { id: "technical", label: "مشكلة تقنية" }, { id: "learning", label: "التعلّم" }, { id: "fitness", label: "Fitness" }, { id: "kids", label: "Kids" }, { id: "billing", label: "الفواتير والاسترداد" }, { id: "privacy", label: "الخصوصية والبيانات" }, { id: "suggestion", label: "اقتراح عام" }];
const statusLabel: Record<string, string> = { new: "جديدة", in_review: "قيد المراجعة", waiting_user: "بانتظارك", resolved: "محلولة", closed: "مغلقة" };

export default function SupportPage() {
  const [tickets, setTickets] = useState<Ticket[]>([]), [product, setProduct] = useState("main"), [category, setCategory] = useState("technical"), [subject, setSubject] = useState(""), [description, setDescription] = useState(""), [notice, setNotice] = useState(""), [loading, setLoading] = useState(true), [submitting, setSubmitting] = useState(false), [signedIn, setSignedIn] = useState(true);
  const load = async () => { setLoading(true); try { const response = await fetch("/api/support/tickets", { cache: "no-store" }); const data = await response.json(); if (response.status === 401) { setSignedIn(false); return; } if (!response.ok) throw new Error(data.error || "تعذر تحميل الدعم"); setTickets(Array.isArray(data.tickets) ? data.tickets : []); } catch (error) { setNotice(error instanceof Error ? error.message : "تعذر تحميل الدعم"); } finally { setLoading(false); } };
  useEffect(() => { const value = new URLSearchParams(window.location.search).get("product") || "main"; if (products.some(item => item.id === value)) setProduct(value); void load(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSubmitting(true); setNotice(""); try { const response = await fetch("/api/support/tickets", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ product, category, subject, description }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "تعذر فتح التذكرة"); setSubject(""); setDescription(""); setNotice("تم فتح تذكرتك. ستظهر أي متابعة داخل هذه الصفحة."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "تعذر فتح التذكرة"); } finally { setSubmitting(false); } };
  return <main className="support-page" dir="rtl"><header><Link href="/">← العودة إلى NAVIXA</Link><div><small>NAVIXA SA</small><h1>الدعم الفني الموحد</h1><p>نقطة مساعدة واحدة لـ NAVIXA وLearning وFitness وKids.</p></div></header><section className="support-safety"><b>لأمان حسابك:</b> لا تكتب كلمة المرور أو رمز OTP أو مفاتيح API أو أرقام البطاقات. لا نطلبها منك عبر الدعم.</section>{!signedIn ? <section className="support-login"><h2>سجّل الدخول أولًا</h2><p>فتح التذكرة ومتابعتها يحتاجان جلسة NAVIXA لحماية حسابك ومنع انتحال الطلبات.</p><Link href="/account">الذهاب إلى الحساب</Link></section> : <div className="support-grid"><section className="support-form"><h2>كيف نساعدك؟</h2><p>اختر المنصة واكتب وصفًا مختصرًا. لا نرسل رسائل خارجية تلقائيًا في هذه المرحلة.</p><form onSubmit={submit}><label>المنصة<select value={product} onChange={event => setProduct(event.target.value)}>{products.map(item => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>التصنيف<select value={category} onChange={event => setCategory(event.target.value)}>{categories.map(item => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>عنوان المشكلة<input value={subject} onChange={event => setSubject(event.target.value)} minLength={4} maxLength={120} required placeholder="مثال: لا يفتح درس اليوم" /></label><label>الوصف<textarea value={description} onChange={event => setDescription(event.target.value)} minLength={12} maxLength={1600} required placeholder="ما الذي حدث؟ وما الخطوة التي سبقت المشكلة؟" /></label><button disabled={submitting}>{submitting ? "جارٍ الإرسال…" : "فتح تذكرة دعم"}</button></form>{notice && <p className="support-notice" role="status">{notice}</p>}</section><section className="support-list"><div><h2>تذاكرك</h2><small>تُحتفظ التذاكر المغلقة 90 يومًا ثم تُحذف تلقائيًا.</small></div>{loading ? <p>جارٍ التحميل…</p> : tickets.length === 0 ? <p className="support-empty">لا توجد تذاكر حتى الآن.</p> : <ul>{tickets.map(ticket => <li key={ticket.id}><div><span className={`support-status ${ticket.status}`}>{statusLabel[ticket.status] || ticket.status}</span><b>{ticket.subject}</b><small>{products.find(item => item.id === ticket.product)?.label || ticket.product} · {new Date(ticket.updated_at).toLocaleDateString("ar-SA")}</small></div>{ticket.admin_reply && <p><strong>رد الدعم:</strong> {ticket.admin_reply}</p>}</li>)}</ul>}</section></div>}</main>;
}
